import { AirlineType } from "./models";

export const airlinesData: AirlineType[] =
  [
    { "country": "Singapore", "name": "Abacus International", "icao": "" },
    { "country": "South Africa", "name": "1Time Airline", "icao": "RNX" },
    { "country": "United States", "name": "40-Mile Air", "icao": "MLA" },
    { "country": "Australia", "name": "Ansett Australia", "icao": "AAA" },
    { "country": "France", "name": "Aigle Azur", "icao": "AAF" },
    { "country": "United States", "name": "Aloha Airlines", "icao": "AAH" },
    { "country": "United States", "name": "American Airlines", "icao": "AAL" },
    { "country": "Republic of Korea", "name": "Asiana Airlines", "icao": "AAR" },
    { "country": "Pakistan", "name": "Askari Aviation", "icao": "AAS" },
    { "country": "Libya", "name": "Afriqiyah Airways", "icao": "AAW" },
    { "country": "United States", "name": "Allegiant Air", "icao": "AAY" },
    { "country": "Brazil", "name": "ABSA - Aerolinhas Brasileiras", "icao": "TUS" },
    { "country": "Kenya", "name": "Astral Aviation", "icao": "ACP" },
    { "country": "Canadian Territories", "name": "Air Tindi", "icao": "" },
    { "country": "Albania", "name": "Ada Air", "icao": "ADE" },
    { "country": "Slovenia", "name": "Adria Airways", "icao": "ADR" },
    { "country": "Spain", "name": "Air Europa", "icao": "AEA" },
    { "country": "Benin", "name": "Aero Benin", "icao": "AEB" },
    { "country": "Greece", "name": "Aegean Airlines", "icao": "AEE" },
    { "country": "Italy", "name": "Air Europe", "icao": "AEL" },
    { "country": "United States", "name": "Alaska Central Express", "icao": "AER" },
    { "country": "Colombia", "name": "ACES Colombia", "icao": "AES" },
    { "country": "United Kingdom", "name": "Astraeus", "icao": "AEU" },
    { "country": "Ukraine", "name": "Aerosvit Airlines", "icao": "AEW" },
    { "country": "Italy", "name": "Air Italy", "icao": "AEY" },
    { "country": "Australia", "name": "Alliance Airlines", "icao": "UTY" },
    { "country": "Afghanistan", "name": "Ariana Afghan Airlines", "icao": "AFG" },
    { "country": "Russia", "name": "Aeroflot Russian Airlines", "icao": "AFL" },
    { "country": "Bosnia and Herzegovina", "name": "Air Bosna", "icao": "BON" },
    { "country": "France", "name": "Air France", "icao": "AFR" },
    { "country": "France", "name": "Air Caledonie International", "icao": "ACI" },
    { "country": "Sierra Leone", "name": "Air Salone", "icao": "" },
    { "country": "United States", "name": "Air Cargo Carriers", "icao": "SNC" },
    { "country": "Namibia", "name": "Air Namibia", "icao": "NMB" },
    { "country": "Mexico", "name": "Aerolitoral", "icao": "SLI" },
    { "country": "Switzerland", "name": "Air Glaciers", "icao": "AGV" },
    { "country": "Serbia", "name": "Aviogenex", "icao": "AGX" },
    { "country": "Peru", "name": "Aeroper", "icao": "PLI" },
    { "country": "Morocco", "name": "Atlas Blue", "icao": "BMM" },
    { "country": "Azerbaijan", "name": "Azerbaijan Airlines", "icao": "AHY" },
    { "country": "Estonia", "name": "Avies", "icao": "AIA" },
    { "country": "Pakistan", "name": "Airblue", "icao": "ABQ" },
    { "country": "United States", "name": "Airlift International", "icao": "AIR" },
    { "country": "Germany", "name": "Air Berlin", "icao": "BER" },
    { "country": "India", "name": "Air India Limited", "icao": "AIC" },
    { "country": "Reunion", "name": "Air Bourbon", "icao": "BUB" },
    { "country": "Iceland", "name": "Air Atlanta Icelandic", "icao": "ABD" },
    { "country": "France", "name": "Air Tahiti Nui", "icao": "THT" },
    { "country": "Israel", "name": "Arkia Israel Airlines", "icao": "AIZ" },
    { "country": "Jamaica", "name": "Air Jamaica", "icao": "AJM" },
    { "country": "Italy", "name": "Air One", "icao": "ADH" },
    { "country": "India", "name": "Air Sahara", "icao": "RSH" },
    { "country": "Malta", "name": "Air Malta", "icao": "AMC" },
    { "country": "Japan", "name": "Air Japan", "icao": "AJX" },
    { "country": "Republic of Korea", "name": "Air Korea Co. Ltd.", "icao": "AKA" },
    { "country": "Kiribati", "name": "Air Kiribati", "icao": "AKL" },
    { "country": "United States", "name": "America West Airlines", "icao": "AWE" },
    { "country": "United States", "name": "Air Wisconsin", "icao": "AWI" },
    { "country": "Russia", "name": "Tatarstan Airlines", "icao": "TAK" },
    { "country": "United States", "name": "Allegheny Commuter Airlines", "icao": "ALO" },
    { "country": "United States", "name": "Air Sunshine", "icao": "RSI" },
    { "country": "France", "name": "Air Libert", "icao": "" },
    { "country": "Malawi", "name": "Air Malawi", "icao": "AML" },
    { "country": "Italy", "name": "Air Sicilia", "icao": "" },
    { "country": "United States", "name": "ATA Airlines", "icao": "AMT" },
    { "country": "Macao", "name": "Air Macau", "icao": "AMU" },
    { "country": "Egypt", "name": "AMC Airlines", "icao": "AMV" },
    { "country": "Seychelles", "name": "Air Seychelles", "icao": "SEY" },
    { "country": "Mexico", "name": "AeroMéxico", "icao": "AMX" },
    { "country": "Japan", "name": "All Nippon Airways", "icao": "ANA" },
    { "country": "Spain", "name": "Air Nostrum", "icao": "ANE" },
    { "country": "Papua New Guinea", "name": "Air Niugini", "icao": "ANG" },
    { "country": "United Arab Emirates", "name": "Air Arabia", "icao": "ABY" },
    { "country": "Canada", "name": "Air Canada", "icao": "ACA" },
    { "country": "Latvia", "name": "Air Baltic", "icao": "BTI" },
    { "country": "Japan", "name": "Air Nippon", "icao": "ANK" },
    { "country": "Australia", "name": "Airnorth", "icao": "ANO" },
    { "country": "Canada", "name": "Air North Charter - Canada", "icao": "ANT" },
    { "country": "New Zealand", "name": "Air New Zealand", "icao": "ANZ" },
    { "country": "Italy", "name": "Alitalia Express", "icao": "SMX" },
    { "country": "Germany", "name": "Aero Flight", "icao": "ARF" },
    { "country": "United States", "name": "Arrow Air", "icao": "APW" },
    { "country": "Portugal", "name": "Aerocondor", "icao": "ARD" },
    { "country": "S.A.", "name": "Aires", "icao": "ARE" },
    { "country": "Argentina", "name": "Aerolineas Argentinas", "icao": "ARG" },
    { "country": "United States", "name": "Alaska Airlines", "icao": "ASA" },
    { "country": "Egypt", "name": "Air Sinai", "icao": "ASD" },
    { "country": "United States", "name": "Atlantic Southeast Airlines", "icao": "ASQ" },
    { "country": "Russia", "name": "Astrakhan Airlines", "icao": "ASZ" },
    { "country": "Tanzania", "name": "Air Tanzania", "icao": "ATC" },
    { "country": "Burkina Faso", "name": "Air Burkina", "icao": "VBW" },
    { "country": "Australia", "name": "Airlines Of Tasmania", "icao": "ATM" },
    { "country": "France", "name": "Air Saint Pierre", "icao": "SPM" },
    { "country": "Austria", "name": "Austrian Airlines", "icao": "AUA" },
    { "country": "United Kingdom", "name": "Air Southwest", "icao": "WOW" },
    { "country": "Germany", "name": "Augsburg Airways", "icao": "AUB" },
    { "country": "Ecuador", "name": "ATUR", "icao": "TUR" },
    { "country": "United Arab Emirates", "name": "Abu Dhabi Amiri Flight", "icao": "AUH" },
    { "country": "Russia", "name": "Aeroflot-Nord", "icao": "AUL" },
    { "country": "United Kingdom", "name": "Aurigny Air Services", "icao": "AUR" },
    { "country": "Argentina", "name": "Austral Lineas Aereas", "icao": "AUT" },
    { "country": "AVIANCA", "name": "Avianca - Aerovias Nacionales de Colombia", "icao": "AVA" },
    { "country": "Vanuatu", "name": "Air Vanuatu", "icao": "AVN" },
    { "country": "Bangladesh", "name": "Air Bangladesh", "icao": "BGD" },
    { "country": "France", "name": "Air Mediterranee", "icao": "BIE" },
    { "country": "France", "name": "Air Moorea", "icao": "TAH" },
    { "country": "Germany", "name": "Aeroline GmbH", "icao": "AWU" },
    { "country": "United Kingdom", "name": "Air Wales", "icao": "AWW" },
    { "country": "France", "name": "Air Caraïbes", "icao": "FWI" },
    { "country": "India", "name": "Air India Express", "icao": "AXB" },
    { "country": "Netherlands", "name": "Air Exel", "icao": "AXL" },
    { "country": "Malaysia", "name": "AirAsia", "icao": "AXM" },
    { "country": "Russia", "name": "Atlant-Soyuz Airlines", "icao": "AYZ" },
    { "country": "Italy", "name": "Alitalia", "icao": "AZA" },
    { "country": "Bolivia", "name": "Amaszonas", "icao": "AZN" },
    { "country": "Zimbabwe", "name": "Air Zimbabwe", "icao": "AZW" },
    { "country": "Venezuela", "name": "Aserca Airlines", "icao": "OCA" },
    { "country": "Russia", "name": "Rossiya-Russian Airlines", "icao": "SDM" },
    { "country": "United States", "name": "American Eagle Airlines", "icao": "EGF" },
    { "country": "United Kingdom", "name": "AD Aviation", "icao": "VUE" },
    { "country": "Ivory Coast", "name": "Air Ivoire", "icao": "VUN" },
    { "country": "Botswana", "name": "Air Botswana", "icao": "BOT" },
    { "country": "United Kingdom", "name": "Air Foyle", "icao": "UPA" },
    { "country": "French Polynesia", "name": "Air Tahiti", "icao": "VTA" },
    { "country": "Bulgaria", "name": "Air VIA", "icao": "VIM" },
    { "country": "Togo", "name": "Africa West", "icao": "WTA" },
    { "country": "Russian Federation", "name": "ATRAN Cargo Airlines", "icao": "VAS" },
    { "country": "China", "name": "Air China", "icao": "CCA" },
    { "country": "Peru", "name": "Aero Condor Peru", "icao": "CDP" },
    { "country": "New Zealand", "name": "Air Chathams", "icao": "CVA" },
    { "country": "Marshall Islands", "name": "Air Marshall Islands", "icao": "CWM" },
    { "country": "United States", "name": "Access Air", "icao": "CYD" },
    { "country": "Algeria", "name": "Air Algerie", "icao": "DAH" },
    { "country": "Indonesia", "name": "Adam Air", "icao": "DHI" },
    { "country": "Italy", "name": "Air Dolomiti", "icao": "DLA" },
    { "country": "Russia", "name": "Aeroflot-Don", "icao": "DNV" },
    { "country": "Spain", "name": "Air Madrid", "icao": "DRD" },
    { "country": "Spain", "name": "Madrid - Adolfo Suárez", "icao": "MAD" },
    { "country": "Ireland", "name": "Aer Lingus", "icao": "EIN" },
    { "country": "Finland", "name": "Air Finland", "icao": "FIF" },
    { "country": "Finland", "name": "Airfix Aviation", "icao": "FIX" },
    { "country": "Fiji", "name": "Air Pacific", "icao": "FJI" },
    { "country": "Faroe Islands", "name": "Atlantic Airways", "icao": "FLI" },
    { "country": "United States", "name": "Air Florida", "icao": "FLZ" },
    { "country": "Iceland", "name": "Air Iceland", "icao": "FXI" },
    { "country": "Philippines", "name": "Air Philippines", "icao": "GAP" },
    { "country": "Guinea", "name": "Air Guinee Express", "icao": "GIP" },
    { "country": "Denmark", "name": "Air Greenland", "icao": "GRL" },
    { "country": "United States", "name": "Atlas Air", "icao": "GTI" },
    { "country": "French Guiana", "name": "Air Guyane", "icao": "GUY" },
    { "country": "Myanmar", "name": "Air Bagan", "icao": "JAB" },
    { "country": "Canada", "name": "Air Canada Jazz", "icao": "JZA" },
    { "country": "Turkey", "name": "Atlasjet", "icao": "KKK" },
    { "country": "Democratic People Republic of Korea", "name": "Air Koryo", "icao": "KOR" },
    { "country": "Kazakhstan", "name": "Air Astana", "icao": "KZR" },
    { "country": "Albania", "name": "Albanian Airlines", "icao": "LBC" },
    { "country": "Turkey", "name": "Air Alfa", "icao": "LFA" },
    { "country": "Ecuador", "name": "Aerolane", "icao": "LNE" },
    { "country": "Armenia", "name": "Atlantis European Airways", "icao": "LUR" },
    { "country": "Portugal", "name": "Air Luxor", "icao": "LXR" },
    { "country": "Mauritius", "name": "Air Mauritius", "icao": "MAU" },
    { "country": "Madagascar", "name": "Air Madagascar", "icao": "MDG" },
    { "country": "Moldova", "name": "Air Moldova", "icao": "MLD" },
    { "country": "Denmark", "name": "Alsie Express", "icao": "MMD" },
    { "country": "Spain", "name": "Air Plus Comet", "icao": "MPD" },
    { "country": "Russian Federation", "name": "Astair", "icao": "" },
    { "country": "Nigeria", "name": "Aero Contractors", "icao": "NIG" },
    { "country": "Australia", "name": "Aeropelican Air Services", "icao": "PEL" },
    { "country": "Ireland", "name": "Aer Arann", "icao": "REA" },
    { "country": "France", "name": "Air Austral", "icao": "REU" },
    { "country": "Philippines", "name": "Asian Spirit", "icao": "RIT" },
    { "country": "Ivory Coast", "name": "Air Afrique", "icao": "RKA" },
    { "country": "France", "name": "Airlinair", "icao": "RLA" },
    { "country": "Sri Lanka", "name": "Aero Lanka", "icao": "RLN" },
    { "country": "Sierra Leone", "name": "Air Salone", "icao": "RNE" },
    { "country": "Armenia", "name": "Armavia", "icao": "RNV" },
    { "country": "Colombia", "name": "AeroRep", "icao": "RPB" },
    { "country": "Republic of the Congo", "name": "Aero-Service", "icao": "RSR" },
    { "country": "Bolivia", "name": "Aerosur", "icao": "RSU" },
    { "country": "Portugal", "name": "Aeronorte", "icao": "RTE" },
    { "country": "Zimbabwe", "name": "Avient Aviation", "icao": "SMJ" },
    { "country": "Russia", "name": "Aircompany Yakutia", "icao": "SYL" },
    { "country": "Mexico", "name": "Aeromar", "icao": "TAO" },
    { "country": "Netherlands", "name": "Arkefly", "icao": "TFL" },
    { "country": "Papua New Guinea", "name": "Airlines PNG", "icao": "TOK" },
    { "country": "United States", "name": "AirTran Airways", "icao": "TRS" },
    { "country": "Canada", "name": "Air Transat", "icao": "TSC" },
    { "country": "Uzbekistan", "name": "Avialeasing Aviation Company", "icao": "TWN" },
    { "country": "Austria", "name": "Tyrolean Airways", "icao": "TYR" },
    { "country": "Ecuador", "name": "Aerolineas Galapagos (Aerogal)", "icao": "GLG" },
    { "country": "Russia", "name": "Alrosa Mirny Air Enterprise", "icao": "DRU" },
    { "country": "United Kingdom", "name": "British Airways", "icao": "BAW" },
    { "country": "Bangladesh", "name": "Biman Bangladesh Airlines", "icao": "BBC" },
    { "country": "Switzerland", "name": "Belair Airlines", "icao": "BHP" },
    { "country": "Bahamas", "name": "Bahamasair", "icao": "BHS" },
    { "country": "", "name": "Balkan Bulgarian Airlines", "icao": "" },
    { "country": "United Kingdom", "name": "British International Helicopters", "icao": "BIH" },
    { "country": "Finland", "name": "BF-Lento OY", "icao": "BKF" },
    { "country": "Thailand", "name": "Bangkok Airways", "icao": "BKP" },
    { "country": "Finland", "name": "Blue1", "icao": "BLF" },
    { "country": "Russia", "name": "Baltic Airlines", "icao": "BLL" },
    { "country": "Canada", "name": "Bearskin Lake Air Service", "icao": "BLS" },
    { "country": "Nigeria", "name": "Bellview Airlines", "icao": "BLV" },
    { "country": "United Kingdom", "name": "bmi", "icao": "BMA" },
    { "country": "United Kingdom", "name": "bmibaby", "icao": "BMI" },
    { "country": "United States", "name": "Bemidji Airlines", "icao": "BMJ" },
    { "country": "United Kingdom", "name": "British Midland Regional", "icao": "BMR" },
    { "country": "Italy", "name": "Blue Panorama Airlines", "icao": "BPA" },
    { "country": "Hungary", "name": "Budapest Aircraft Services/Manx2", "icao": "BPS" },
    { "country": "United States", "name": "Bering Air", "icao": "BRG" },
    { "country": "Brazil", "name": "Brazilian Air Force", "icao": "BRS" },
    { "country": "Belarus", "name": "Belavia Belarusian Airlines", "icao": "BRU" },
    { "country": "Indonesia", "name": "Metro Batavia", "icao": "BTV" },
    { "country": "Malaysia", "name": "Berjaya Air", "icao": "BVT" },
    { "country": "Germany", "name": "Blue Wings", "icao": "BWG" },
    { "country": "France", "name": "Brit Air", "icao": "BZH" },
    { "country": "Belgium", "name": "Brussels Airlines", "icao": "DAT" },
    { "country": "Spain", "name": "Binter Canarias", "icao": "IBB" },
    { "country": "Romania", "name": "Blue Air", "icao": "JOR" },
    { "country": "United Kingdom", "name": "British Mediterranean Airways", "icao": "LAJ" },
    { "country": "Bulgaria", "name": "Bulgaria Air", "icao": "LZB" },
    { "country": "Sweden", "name": "Barents AirLink", "icao": "NKF" },
    { "country": "Israel", "name": "CAL Cargo Air Lines", "icao": "ICL" },
    { "country": "Spain", "name": "Calima Aviacion", "icao": "CLI" },
    { "country": "Canada", "name": "Canadian Airlines", "icao": "CDN" },
    { "country": "Canada", "name": "Canadian North", "icao": "MPE" },
    { "country": "United States", "name": "Cape Air", "icao": "KAP" },
    { "country": "Trinidad and Tobago", "name": "Caribbean Airlines", "icao": "BWA" },
    { "country": "Romania", "name": "Carpatair", "icao": "KRP" },
    { "country": "Iran", "name": "Caspian Airlines", "icao": "CPN" },
    { "country": "Hong Kong SAR of China", "name": "Cathay Pacific", "icao": "CPA" },
    { "country": "Cayman Islands", "name": "Cayman Airways", "icao": "CAY" },
    { "country": "Philippines", "name": "Cebu Pacific", "icao": "CEB" },
    { "country": "Czech Republic", "name": "Central Connect Airlines", "icao": "CCG" },
    { "country": "Poland", "name": "Centralwings", "icao": "CLW" },
    { "country": "Austria", "name": "Charter Air", "icao": "CHW" },
    { "country": "United States", "name": "Chautauqua Airlines", "icao": "CHQ" },
    { "country": "Taiwan", "name": "China Airlines", "icao": "CAL" },
    { "country": "China", "name": "China Eastern Airlines", "icao": "CES" },
    { "country": "China", "name": "China Southern Airlines", "icao": "CSN" },
    { "country": "China", "name": "China United Airlines", "icao": "CUA" },
    { "country": "China", "name": "Yunnan Airlines", "icao": "CYH" },
    { "country": "Denmark", "name": "Cimber Air", "icao": "CIM" },
    { "country": "Germany", "name": "Cirrus Airlines", "icao": "RUS" },
    { "country": "Sweden", "name": "City Airline", "icao": "SDR" },
    { "country": "Burundi", "name": "City Connexion Airlines", "icao": "CIX" },
    { "country": "Ireland", "name": "CityJet", "icao": "BCY" },
    { "country": "United Kingdom", "name": "BA CityFlyer", "icao": "CFE" },
    { "country": "Kyrgyzstan", "name": "Click Airways", "icao": "CGK" },
    { "country": "United States", "name": "Coastal Air", "icao": "" },
    { "country": "United States", "name": "Colgan Air", "icao": "CJC" },
    { "country": "United States", "name": "Comair", "icao": "COM" },
    { "country": "South Africa", "name": "Comair", "icao": "CAW" },
    { "country": "United States", "name": "CommutAir", "icao": "UCA" },
    { "country": "Comoros", "name": "Comores Airlines", "icao": "CWK" },
    { "country": "United States", "name": "Compass Airlines", "icao": "CPZ" },
    { "country": "Germany", "name": "Condor Flugdienst", "icao": "CFG" },
    { "country": "Mexico", "name": "Consorcio Aviaxsa", "icao": "CHP" },
    { "country": "Germany", "name": "Contact Air", "icao": "KIS" },
    { "country": "United States", "name": "Continental Airlines", "icao": "COA" },
    { "country": "United States", "name": "Continental Express", "icao": "" },
    { "country": "United States", "name": "Continental Micronesia", "icao": "CMI" },
    { "country": "Venezuela", "name": "Conviasa", "icao": "VCV" },
    { "country": "Panama", "name": "Copa Airlines", "icao": "CMP" },
    { "country": "Finland", "name": "Copterline", "icao": "AAQ" },
    { "country": "Turkey", "name": "Corendon Airlines", "icao": "CAI" },
    { "country": "France", "name": "Corsairfly", "icao": "CRL" },
    { "country": "France", "name": "Corse-Mediterranee", "icao": "CCM" },
    { "country": "United Kingdom", "name": "Crest Aviation", "icao": "CAN" },
    { "country": "Croatia", "name": "Croatia Airlines", "icao": "CTN" },
    { "country": "United States", "name": "Crown Airways", "icao": "CRO" },
    { "country": "Cuba", "name": "Cubana de Aviación", "icao": "CUB" },
    { "country": "Cyprus", "name": "Cyprus Airways", "icao": "CYP" },
    { "country": "Turkey", "name": "Cyprus Turkish Airlines", "icao": "" },
    { "country": "Czech Republic", "name": "Czech Airlines", "icao": "CSA" },
    { "country": "Denmark", "name": "DAT Danish Air Transport", "icao": "DTR" },
    { "country": "Djibouti", "name": "Daallo Airlines", "icao": "DAO" },
    { "country": "Russia", "name": "Dalavia", "icao": "KHB" },
    { "country": "Switzerland", "name": "Darwin Airline", "icao": "DWT" },
    { "country": "Italy", "name": "Delta Aerotaxi", "icao": "DEA" },
    { "country": "United States", "name": "Delta Air Lines", "icao": "DAL" },
    { "country": "Netherlands", "name": "Denim Air", "icao": "DNM" },
    { "country": "Germany", "name": "Deutsche Bahn", "icao": "" },
    { "country": "Djibouti", "name": "Djibouti Airlines", "icao": "DJB" },
    { "country": "Ukraine", "name": "Dniproavia", "icao": "UDN" },
    { "country": "Dominican Republic", "name": "Dominicana de Aviaci", "icao": "DOA" },
    { "country": "Russia", "name": "Domodedovo Airlines", "icao": "DMO" },
    { "country": "Ukraine", "name": "DonbassAero", "icao": "UDC" },
    { "country": "DRAGON", "name": "Dragonair", "icao": "HDA" },
    { "country": "Bhutan", "name": "Druk Air", "icao": "DRK" },
    { "country": "Croatia", "name": "Dubrovnik Air", "icao": "DBK" },
    { "country": "Netherlands Antilles", "name": "Dutch Antilles Express", "icao": "DNL" },
    { "country": "Germany", "name": "dba", "icao": "BAG" },
    { "country": "Taiwan", "name": "EVA Air", "icao": "EVA" },
    { "country": "Uganda", "name": "Eagle Air", "icao": "" },
    { "country": "Uganda", "name": "East African", "icao": "UGX" },
    { "country": "United Kingdom", "name": "Eastern Airways", "icao": "EZE" },
    { "country": "Australia", "name": "Eastland Air", "icao": "ELA" },
    { "country": "Ecuador", "name": "Ecuavia", "icao": "ECU" },
    { "country": "Switzerland", "name": "Edelweiss Air", "icao": "EDW" },
    { "country": "Egypt", "name": "Egyptair", "icao": "MSR" },
    { "country": "Israel", "name": "El Al Israel Airlines", "icao": "ELY" },
    { "country": "Libya", "name": "El-Buraq Air Transport", "icao": "BRQ" },
    { "country": "United Arab Emirates", "name": "Emirates", "icao": "UAE" },
    { "country": "Ecuador", "name": "Empresa Ecuatoriana De Aviacion", "icao": "EEA" },
    { "country": "Eritrea", "name": "Eritrean Airlines", "icao": "ERT" },
    { "country": "Estonia", "name": "Estonian Air", "icao": "ELL" },
    { "country": "Ethiopia", "name": "Ethiopian Airlines", "icao": "ETH" },
    { "country": "United Arab Emirates", "name": "Etihad Airways", "icao": "ETD" },
    { "country": "Sweden", "name": "Euro Exec Express", "icao": "" },
    { "country": "Cyprus", "name": "Eurocypria Airlines", "icao": "ECA" },
    { "country": "Italy", "name": "Eurofly Service", "icao": "EEU" },
    { "country": "Poland", "name": "Eurolot", "icao": "ELO" },
    { "country": "Germany", "name": "European Air Express", "icao": "EAL" },
    { "country": "Germany", "name": "Eurowings", "icao": "EWG" },
    { "country": "United States", "name": "Evergreen International Airlines", "icao": "EIA" },
    { "country": "United Kingdom", "name": "Excel Airways", "icao": "XLA" },
    { "country": "United Kingdom", "name": "Excel Charter", "icao": "XEL" },
    { "country": "United States", "name": "Express One International", "icao": "LHN" },
    { "country": "United States", "name": "ExpressJet", "icao": "BTA" },
    { "country": "United Kingdom", "name": "easyJet", "icao": "EZY" },
    { "country": "Taiwan", "name": "Far Eastern Air Transport", "icao": "EFA" },
    { "country": "Finland", "name": "Finnair", "icao": "FIN" },
    { "country": "Finland", "name": "Finncomm Airlines", "icao": "WBA" },
    { "country": "Malaysia", "name": "Firefly", "icao": "FFM" },
    { "country": "Canada", "name": "First Air", "icao": "FAB" },
    { "country": "United Kingdom", "name": "First Choice Airways", "icao": "FCA" },
    { "country": "United Kingdom", "name": "Flightline", "icao": "FLT" },
    { "country": "United States", "name": "Florida West International Airways", "icao": "FWL" },
    { "country": "Malaysia", "name": "AirAsia X", "icao": "XAX" },
    { "country": "Lithuania", "name": "FlyLal", "icao": "LIL" },
    { "country": "Sweden", "name": "FlyNordic", "icao": "NDC" },
    { "country": "Switzerland", "name": "Flybaboo", "icao": "BBO" },
    { "country": "United Kingdom", "name": "Flybe", "icao": "BEE" },
    { "country": "United Kingdom", "name": "Flyglobespan", "icao": "GSM" },
    { "country": "Thailand", "name": "Flyhy Cargo Airlines", "icao": "FYH" },
    { "country": "Taiwan", "name": "Formosa Airlines", "icao": "FOS" },
    { "country": "United States", "name": "Freedom Air", "icao": "FRE" },
    { "country": "United States", "name": "Freedom Airlines", "icao": "FRL" },
    { "country": "United States", "name": "Frontier Airlines", "icao": "FFT" },
    { "country": "United States", "name": "Frontier Flying Service", "icao": "FTA" },
    { "country": "United Kingdom", "name": "GB Airways", "icao": "GBL" },
    { "country": "Indonesia", "name": "Garuda Indonesia", "icao": "GIA" },
    { "country": "Russia", "name": "Gazpromavia", "icao": "GZP" },
    { "country": "Georgia", "name": "Georgian Airways", "icao": "TGZ" },
    { "country": "Georgia", "name": "Georgian National Airlines", "icao": "GFG" },
    { "country": "Germany", "name": "Germania", "icao": "GMI" },
    { "country": "Germany", "name": "Germanwings", "icao": "GWI" },
    { "country": "Ghana", "name": "Ghana International Airlines", "icao": "GHB" },
    { "country": "India", "name": "Go Air", "icao": "GOW" },
    { "country": "United States", "name": "GoJet Airlines", "icao": "GJS" },
    { "country": "Brazil", "name": "Gol Transportes Aéreos", "icao": "GLO" },
    { "country": "Sweden", "name": "Golden Air", "icao": "GAO" },
    { "country": "United States", "name": "Great Lakes Airlines", "icao": "GLA" },
    { "country": "Costa Rica", "name": "Grupo TACA", "icao": "TAT" },
    { "country": "Oman", "name": "Gulf Air", "icao": "GFA" },
    { "country": "Bahrain", "name": "Gulf Air Bahrain", "icao": "GBA" },
    { "country": "United States", "name": "Gulfstream International Airlines", "icao": "GFT" },
    { "country": "United States", "name": "Hageland Aviation Services", "icao": "HAG" },
    { "country": "China", "name": "Hainan Airlines", "icao": "CHH" },
    { "country": "Haiti", "name": "Haiti Ambassador Airlines", "icao": "HAM" },
    { "country": "Germany", "name": "Hamburg International", "icao": "HHI" },
    { "country": "Germany", "name": "TUIfly", "icao": "HLX" },
    { "country": "Germany", "name": "Hapagfly", "icao": "HLF" },
    { "country": "United States", "name": "Hawaiian Airlines", "icao": "HAL" },
    { "country": "Canada", "name": "Hawkair", "icao": "" },
    { "country": "France", "name": "Heli France", "icao": "HFR" },
    { "country": "Canada", "name": "Helijet", "icao": "JBA" },
    { "country": "Greece", "name": "Hellas Jet", "icao": "HEJ" },
    { "country": "Switzerland", "name": "Hello", "icao": "FHE" },
    { "country": "Switzerland", "name": "Helvetic Airways", "icao": "OAW" },
    { "country": "France", "name": "Hex Air", "icao": "HER" },
    { "country": "United Kingdom", "name": "Highland Airways", "icao": "HWY" },
    { "country": "Japan", "name": "Hokkaido International Airlines", "icao": "ADO" },
    { "country": "Hong Kong SAR of China", "name": "Hong Kong Airlines", "icao": "CRK" },
    { "country": "Hong Kong SAR of China", "name": "Hong Kong Express Airways", "icao": "HKE" },
    { "country": "United States", "name": "Horizon Air", "icao": "QXE" },
    { "country": "Australia", "name": "Horizon Airlines", "icao": "HZA" },
    { "country": "Spain", "name": "Iberia Airlines", "icao": "IBE" },
    { "country": "Spain", "name": "Iberworld", "icao": "IWD" },
    { "country": "Japan", "name": "Ibex Airlines", "icao": "IBX" },
    { "country": "Bosnia and Herzegovina", "name": "Icar Air", "icao": "RAC" },
    { "country": "Iceland", "name": "Icelandair", "icao": "ICE" },
    { "country": "Azerbaijan", "name": "Imair Airlines", "icao": "ITX" },
    { "country": "India", "name": "IndiGo Airlines", "icao": "IGO" },
    { "country": "India", "name": "Indian Airlines", "icao": "IAC" },
    { "country": "United States", "name": "Indigo", "icao": "IBU" },
    { "country": "Indonesia", "name": "Indonesia AirAsia", "icao": "AWQ" },
    { "country": "Indonesia", "name": "Indonesian Airlines", "icao": "IAA" },
    { "country": "South Africa", "name": "Interair South Africa", "icao": "ILN" },
    { "country": "Russia", "name": "Interavia Airlines", "icao": "SUW" },
    { "country": "South Africa", "name": "Interlink Airlines", "icao": "ITK" },
    { "country": "Austria", "name": "Intersky", "icao": "ISK" },
    { "country": "Iran", "name": "Iran Air", "icao": "IRA" },
    { "country": "Iran", "name": "Iran Aseman Airlines", "icao": "IRC" },
    { "country": "Iraq", "name": "Iraqi Airways", "icao": "IAW" },
    { "country": "United States", "name": "Island Airlines", "icao": "" },
    { "country": "United Arab Emirates", "name": "Cargo Plus Aviation", "icao": "CGP" },
    { "country": "Spain", "name": "Islas Airways", "icao": "ISW" },
    { "country": "Honduras", "name": "Islena De Inversiones", "icao": "ISV" },
    { "country": "Israel", "name": "Israir", "icao": "ISR" },
    { "country": "Kyrgyzstan", "name": "Itek Air", "icao": "IKA" },
    { "country": "Japan", "name": "JAL Express", "icao": "JEX" },
    { "country": "Japan", "name": "JALways", "icao": "JAZ" },
    { "country": "Japan", "name": "Japan Airlines", "icao": "JAL" },
    { "country": "Japan", "name": "Japan Airlines Domestic", "icao": "JAL" },
    { "country": "United Kingdom", "name": "easyJet", "icao": "EZY" },
    { "country": "Taiwan", "name": "Far Eastern Air Transport", "icao": "EFA" },
    { "country": "Finland", "name": "Finnair", "icao": "FIN" },
    { "country": "Finland", "name": "Finncomm Airlines", "icao": "WBA" },
    { "country": "Malaysia", "name": "Firefly", "icao": "FFM" },
    { "country": "Canada", "name": "First Air", "icao": "FAB" },
    { "country": "United Kingdom", "name": "First Choice Airways", "icao": "FCA" },
    { "country": "United Kingdom", "name": "Flightline", "icao": "FLT" },
    { "country": "United States", "name": "Florida West International Airways", "icao": "FWL" },
    { "country": "Malaysia", "name": "AirAsia X", "icao": "XAX" },
    { "country": "Lithuania", "name": "FlyLal", "icao": "LIL" },
    { "country": "Sweden", "name": "FlyNordic", "icao": "NDC" },
    { "country": "Switzerland", "name": "Flybaboo", "icao": "BBO" },
    { "country": "United Kingdom", "name": "Flybe", "icao": "BEE" },
    { "country": "United Kingdom", "name": "Flyglobespan", "icao": "GSM" },
    { "country": "Thailand", "name": "Flyhy Cargo Airlines", "icao": "FYH" },
    { "country": "Taiwan", "name": "Formosa Airlines", "icao": "FOS" },
    { "country": "United States", "name": "Freedom Air", "icao": "FRE" },
    { "country": "United States", "name": "Freedom Airlines", "icao": "FRL" },
    { "country": "United States", "name": "Frontier Airlines", "icao": "FFT" },
    { "country": "United States", "name": "Frontier Flying Service", "icao": "FTA" },
    { "country": "United Kingdom", "name": "GB Airways", "icao": "GBL" },
    { "country": "Indonesia", "name": "Garuda Indonesia", "icao": "GIA" },
    { "country": "Russia", "name": "Gazpromavia", "icao": "GZP" },
    { "country": "Georgia", "name": "Georgian Airways", "icao": "TGZ" },
    { "country": "Georgia", "name": "Georgian National Airlines", "icao": "GFG" },
    { "country": "Germany", "name": "Germania", "icao": "GMI" },
    { "country": "Germany", "name": "Germanwings", "icao": "GWI" },
    { "country": "Ghana", "name": "Ghana International Airlines", "icao": "GHB" },
    { "country": "India", "name": "Go Air", "icao": "GOW" },
    { "country": "United States", "name": "GoJet Airlines", "icao": "GJS" },
    { "country": "Brazil", "name": "Gol Transportes Aéreos", "icao": "GLO" },
    { "country": "Sweden", "name": "Golden Air", "icao": "GAO" },
    { "country": "United States", "name": "Great Lakes Airlines", "icao": "GLA" },
    { "country": "Costa Rica", "name": "Grupo TACA", "icao": "TAT" },
    { "country": "Oman", "name": "Gulf Air", "icao": "GFA" },
    { "country": "Bahrain", "name": "Gulf Air Bahrain", "icao": "GBA" },
    { "country": "United States", "name": "Gulfstream International Airlines", "icao": "GFT" },
    { "country": "United States", "name": "Hageland Aviation Services", "icao": "HAG" },
    { "country": "China", "name": "Hainan Airlines", "icao": "CHH" },
    { "country": "Haiti", "name": "Haiti Ambassador Airlines", "icao": "HAM" },
    { "country": "Germany", "name": "Hamburg International", "icao": "HHI" },
    { "country": "Germany", "name": "TUIfly", "icao": "HLX" },
    { "country": "Germany", "name": "Hapagfly", "icao": "HLF" },
    { "country": "United States", "name": "Hawaiian Airlines", "icao": "HAL" },
    { "country": "Canada", "name": "Hawkair", "icao": "" },
    { "country": "France", "name": "Heli France", "icao": "HFR" },
    { "country": "Canada", "name": "Helijet", "icao": "JBA" },
    { "country": "Greece", "name": "Hellas Jet", "icao": "HEJ" },
    { "country": "Switzerland", "name": "Hello", "icao": "FHE" },
    { "country": "Switzerland", "name": "Helvetic Airways", "icao": "OAW" },
    { "country": "France", "name": "Hex Air", "icao": "HER" },
    { "country": "United Kingdom", "name": "Highland Airways", "icao": "HWY" },
    { "country": "Japan", "name": "Hokkaido International Airlines", "icao": "ADO" },
    { "country": "Hong Kong SAR of China", "name": "Hong Kong Airlines", "icao": "CRK" },
    { "country": "Hong Kong SAR of China", "name": "Hong Kong Express Airways", "icao": "HKE" },
    { "country": "United States", "name": "Horizon Air", "icao": "QXE" },
    { "country": "Australia", "name": "Horizon Airlines", "icao": "HZA" },
    { "country": "Spain", "name": "Iberia Airlines", "icao": "IBE" },
    { "country": "Spain", "name": "Iberworld", "icao": "IWD" },
    { "country": "Japan", "name": "Ibex Airlines", "icao": "IBX" },
    { "country": "Bosnia and Herzegovina", "name": "Icar Air", "icao": "RAC" },
    { "country": "Iceland", "name": "Icelandair", "icao": "ICE" },
    { "country": "Azerbaijan", "name": "Imair Airlines", "icao": "ITX" },
    { "country": "India", "name": "IndiGo Airlines", "icao": "IGO" },
    { "country": "India", "name": "Indian Airlines", "icao": "IAC" },
    { "country": "United States", "name": "Indigo", "icao": "IBU" },
    { "country": "Indonesia", "name": "Indonesia AirAsia", "icao": "AWQ" },
    { "country": "Indonesia", "name": "Indonesian Airlines", "icao": "IAA" },
    { "country": "South Africa", "name": "Interair South Africa", "icao": "ILN" },
    { "country": "Russia", "name": "Interavia Airlines", "icao": "SUW" },
    { "country": "South Africa", "name": "Interlink Airlines", "icao": "ITK" },
    { "country": "Austria", "name": "Intersky", "icao": "ISK" },
    { "country": "Iran", "name": "Iran Air", "icao": "IRA" },
    { "country": "Iran", "name": "Iran Aseman Airlines", "icao": "IRC" },
    { "country": "Iraq", "name": "Iraqi Airways", "icao": "IAW" },
    { "country": "United States", "name": "Island Airlines", "icao": "" },
    { "country": "United Arab Emirates", "name": "Cargo Plus Aviation", "icao": "CGP" },
    { "country": "Spain", "name": "Islas Airways", "icao": "ISW" },
    { "country": "Honduras", "name": "Islena De Inversiones", "icao": "ISV" },
    { "country": "Israel", "name": "Israir", "icao": "ISR" },
    { "country": "Kyrgyzstan", "name": "Itek Air", "icao": "IKA" },
    { "country": "Japan", "name": "JAL Express", "icao": "JEX" },
    { "country": "Japan", "name": "JALways", "icao": "JAZ" },
    { "country": "Japan", "name": "Japan Airlines", "icao": "JAL" },
    { "country": "Japan", "name": "Japan Airlines Domestic", "icao": "JAL" },
    { "country": "Japan", "name": "Japan Asia Airways", "icao": "JAA" },
    { "country": "Japan", "name": "Japan Transocean Air", "icao": "JTA" },
    { "country": "Serbia", "name": "Jat Airways", "icao": "JAT" },
    { "country": "Kuwait", "name": "Jazeera Airways", "icao": "JZR" },
    { "country": "Republic of Korea", "name": "Jeju Air", "icao": "JJA" },
    { "country": "India", "name": "Jet Airways", "icao": "JAI" },
    { "country": "United States", "name": "Jet Airways", "icao": "" },
    { "country": "Singapore", "name": "Jetstar Asia Airways", "icao": "JSA" },
    { "country": "United Kingdom", "name": "Jet2.com", "icao": "EXS" },
    { "country": "Morocco", "name": "Jet4You", "icao": "JFU" },
    { "country": "United States", "name": "JetBlue Airways", "icao": "JBU" },
    { "country": "Belgium", "name": "Jetairfly", "icao": "JAF" },
    { "country": "Finland", "name": "Jetflite", "icao": "JEF" },
    { "country": "Australia", "name": "Jetstar Airways", "icao": "JST" },
    { "country": "China", "name": "Juneyao Airlines", "icao": "DKH" },
    { "country": "Russia", "name": "KD Avia", "icao": "KNI" },
    { "country": "Netherlands", "name": "KLM Cityhopper", "icao": "KLC" },
    { "country": "Netherlands", "name": "KLM Royal Dutch Airlines", "icao": "KLM" },
    { "country": "Afghanistan", "name": "Kam Air", "icao": "KMF" },
    { "country": "Russia", "name": "Kavminvodyavia", "icao": "MVD" },
    { "country": "Australia", "name": "Kendell Airlines", "icao": "KDA" },
    { "country": "United States", "name": "Kenmore Air", "icao": "KEN" },
    { "country": "Kenya", "name": "Kenya Airways", "icao": "KQA" },
    { "country": "India", "name": "Kingfisher Airlines", "icao": "KFR" },
    { "country": "Iran", "name": "Kish Air", "icao": "IRK" },
    { "country": "Russia", "name": "Kogalymavia Air Company", "icao": "KGL" },
    { "country": "Republic of Korea", "name": "Korean Air", "icao": "KAL" },
    { "country": "Russia", "name": "Kosmos", "icao": "KSM" },
    { "country": "Russia", "name": "Krasnojarsky Airlines", "icao": "KJC" },
    { "country": "Russia", "name": "Kuban Airlines", "icao": "KIL" },
    { "country": "Kuwait", "name": "Kuwait Airways", "icao": "KAC" },
    { "country": "Turkey", "name": "Kuzu Airlines Cargo", "icao": "KZU" },
    { "country": "Costa Rica", "name": "LACSA", "icao": "LRC" },
    { "country": "Chile", "name": "LAN Airlines", "icao": "LAN" },
    { "country": "Argentina", "name": "LAN Argentina", "icao": "DSM" },
    { "country": "Chile", "name": "LAN Express", "icao": "LXP" },
    { "country": "Peru", "name": "LAN Peru", "icao": "LPE" },
    { "country": "Poland", "name": "LOT Polish Airlines", "icao": "LOT" },
    { "country": "Spain", "name": "LTE International Airways", "icao": "LTE" },
    { "country": "Austria", "name": "LTU Austria", "icao": "LTO" },
    { "country": "Germany", "name": "LTU International", "icao": "LTU" },
    { "country": "Lao Peoples Democratic Republic", "name": "Lao Airlines", "icao": "LAO" },
    { "country": "Latvia", "name": "LatCharter", "icao": "LTC" },
    { "country": "Austria", "name": "Lauda Air", "icao": "LDA" },
    { "country": "Antigua and Barbuda", "name": "Leeward Islands Air Transport", "icao": "LIA" },
    { "country": "Libya", "name": "Libyan Arab Airlines", "icao": "LAA" },
    { "country": "Mozambique", "name": "Linhas A", "icao": "LAM" },
    { "country": "Indonesia", "name": "Lion Mentari Airlines", "icao": "LNI" },
    { "country": "Germany", "name": "Luftfahrtgesellschaft Walter", "icao": "LGW" },
    { "country": "Germany", "name": "Lufthansa", "icao": "DLH" },
    { "country": "Germany", "name": "Lufthansa Cargo", "icao": "GEC" },
    { "country": "Germany", "name": "Lufthansa CityLine", "icao": "CLH" },
    { "country": "Norway", "name": "Lufttransport", "icao": "LTR" },
    { "country": "Luxembourg", "name": "Luxair", "icao": "LGL" },
    { "country": "Argentina", "name": "L", "icao": "LPR" },
    { "country": "Mexico", "name": "MasAir", "icao": "MAA" },
    { "country": "Macedonia", "name": "MAT Macedonian Airlines", "icao": "MAK" },
    { "country": "Mongolia", "name": "MIAT Mongolian Airlines", "icao": "MGL" },
    { "country": "Turkey", "name": "MNG Airlines", "icao": "MNB" },
    { "country": "Australia", "name": "Macair Airlines", "icao": "MCK" },
    { "country": "Denmark", "name": "Maersk", "icao": "" },
    { "country": "Iran", "name": "Mahan Air", "icao": "IRM" },
    { "country": "Malaysia", "name": "Malaysia Airlines", "icao": "MAS" },
    { "country": "Sweden", "name": "Malmo Aviation", "icao": "SCW" },
    { "country": "Sweden", "name": "Malmö Aviation", "icao": "SCW" },
    { "country": "Malta", "name": "Malta Air Charter", "icao": "MAC" },
    { "country": "Hungary", "name": "Malév", "icao": "MAH" },
    { "country": "Indonesia", "name": "Mandala Airlines", "icao": "MDL" },
    { "country": "Taiwan", "name": "Mandarin Airlines", "icao": "MDA" },
    { "country": "South Africa", "name": "Mango", "icao": "MNO" },
    { "country": "Netherlands", "name": "Martinair", "icao": "MPH" },
    { "country": "Sweden", "name": "Maxair", "icao": "MXL" },
    { "country": "Belize", "name": "Maya Island Air", "icao": "MYD" },
    { "country": "Italy", "name": "Meridiana", "icao": "ISS" },
    { "country": "Indonesia", "name": "Merpati Nusantara Airlines", "icao": "MNA" },
    { "country": "United States", "name": "Mesa Airlines", "icao": "ASH" },
    { "country": "United States", "name": "Mesaba Airlines", "icao": "MES" },
    { "country": "Mexico", "name": "Mexicana de Aviaci", "icao": "MXA" },
    { "country": "Lebanon", "name": "Middle East Airlines", "icao": "MEA" },
    { "country": "United States", "name": "Midway Airlines", "icao": "MDW" },
    { "country": "United States", "name": "Midwest Airlines", "icao": "MEP" },
    { "country": "Egypt", "name": "Midwest Airlines (Egypt)", "icao": "MWA" },
    { "country": "Moldova", "name": "Moldavian Airlines", "icao": "MDV" },
    { "country": "United Kingdom", "name": "Monarch Airlines", "icao": "MON" },
    { "country": "Italy", "name": "Myway Airlines", "icao": "" },
    { "country": "Montenegro", "name": "Montenegro Airlines", "icao": "MGX" },
    { "country": "Canada", "name": "Morningstar Air Express", "icao": "MAL" },
    { "country": "Russia", "name": "Moskovia Airlines", "icao": "GAI" },
    { "country": "Ukraine", "name": "Motor Sich", "icao": "MSI" },
    { "country": "United Kingdom", "name": "MyTravel Airways", "icao": "MYT" },
    { "country": "Myanmar", "name": "Myanma Airways", "icao": "UBA" },
    { "country": "Myanmar", "name": "Myanmar Airways International", "icao": "MMM" },
    { "country": "Iceland", "name": "Myflug", "icao": "MYA" },
    { "country": "Eritrea", "name": "Nasair", "icao": "NAS" },
    { "country": "Australia", "name": "National Jet Systems", "icao": "NJS" },
    { "country": "South Africa", "name": "Nationwide Airlines", "icao": "NTW" },
    { "country": "Nauru", "name": "Nauru Air Corporation", "icao": "RON" },
    { "country": "Nepal", "name": "Nepal Airlines", "icao": "RNA" },
    { "country": "United States", "name": "NetJets", "icao": "EJA" },
    { "country": "United States", "name": "New England Airlines", "icao": "NEA" },
    { "country": "Sweden", "name": "NextJet", "icao": "NTJ" },
    { "country": "Austria", "name": "Niki", "icao": "NLY" },
    { "country": "Thailand", "name": "Nok Air", "icao": "NOK" },
    { "country": "United Kingdom", "name": "Norfolk County Flight College", "icao": "NCF" },
    { "country": "Canada", "name": "North American Airlines", "icao": "NTM" },
    { "country": "Canada", "name": "North American Charters", "icao": "HMR" },
    { "country": "Canada", "name": "Northern Dene Airways", "icao": "" },
    { "country": "United States", "name": "Northwest Airlines", "icao": "NWA" },
    { "country": "Canada", "name": "Northwestern Air", "icao": "PLR" },
    { "country": "Norway", "name": "Norwegian Air Shuttle", "icao": "NAX" },
    { "country": "Norway", "name": "Norwegian Aviation College", "icao": "TFN" },
    { "country": "Tunisia", "name": "Nouvel Air Tunisie", "icao": "LBT" },
    { "country": "Sweden", "name": "Novair", "icao": "NVR" },
    { "country": "Saudi Arabia", "name": "Nas Air", "icao": "KNE" },
    { "country": "Hong Kong", "name": "Oasis Hong Kong Airlines", "icao": "OHK" },
    { "country": "Mauritania", "name": "Ocean Air", "icao": "BCN" },
    { "country": "Brazil", "name": "Oceanair", "icao": "ONE" },
    { "country": "Guinea", "name": "Oceanic Airlines", "icao": "" },
    { "country": "Greece", "name": "Olympic Airlines", "icao": "OAL" },
    { "country": "Oman", "name": "Oman Air", "icao": "OMA" },
    { "country": "United States", "name": "Omni Air International", "icao": "OAE" },
    { "country": "Thailand", "name": "One Two Go Airlines", "icao": "OTG" },
    { "country": "Turkey", "name": "Onur Air", "icao": "OHY" },
    { "country": "Russia", "name": "Orenburg Airlines", "icao": "ORB" },
    { "country": "Thailand", "name": "Orient Thai Airlines", "icao": "OEA" },
    { "country": "New Zealand", "name": "Origin Pacific Airways", "icao": "OGN" },
    { "country": "Germany", "name": "Ostfriesische Lufttransport", "icao": "OLT" },
    { "country": "Nigeria", "name": "Overland Airways", "icao": "OLA" },
    { "country": "Australia", "name": "Ozjet Airlines", "icao": "OZJ" },
    { "country": "Spain", "name": "PAN Air", "icao": "PNR" },
    { "country": "Thailand", "name": "PB Air", "icao": "PBA" },
    { "country": "Uruguay", "name": "PLUNA", "icao": "PUA" },
    { "country": "Cambodia", "name": "PMTair", "icao": "PMT" },
    { "country": "Vietnam", "name": "Jetstar Pacific", "icao": "PIC" },
    { "country": "Canada", "name": "Pacific Coastal Airline", "icao": "PCO" },
    { "country": "Philippines", "name": "Pacific East Asia Cargo Airlines", "icao": "PEC" },
    { "country": "United States", "name": "Pacific Island Aviation", "icao": "PSA" },
    { "country": "United States", "name": "Pacific Wings", "icao": "NMI" },
    { "country": "Pakistan", "name": "Pakistan International Airlines", "icao": "PIA" },
    { "country": "India", "name": "Paramount Airways", "icao": "PMW" },
    { "country": "Brazil", "name": "Passaredo Transportes Aereos", "icao": "PTB" },
    { "country": "Turkey", "name": "Pegasus Airlines", "icao": "PGT" },
    { "country": "United States", "name": "Peninsula Airways", "icao": "PEN" },
    { "country": "Philippines", "name": "Philippine Airlines", "icao": "PAL" },
    { "country": "United States", "name": "Piedmont Airlines ", "icao": "PDT" },
    { "country": "United States", "name": "Pinnacle Airlines", "icao": "FLG" },
    { "country": "Russia", "name": "Polet", "icao": "POT" },
    { "country": "Samoa", "name": "Polynesian Airlines", "icao": "PAO" },
    { "country": "Canada", "name": "Porter Airlines", "icao": "POE" },
    { "country": "Portugal", "name": "Portugalia", "icao": "PGA" },
    { "country": "United States", "name": "Potomac Air", "icao": "PDC" },
    { "country": "Tanzania", "name": "Precision Air", "icao": "PRF" },
    { "country": "Switzerland", "name": "Privatair", "icao": "PTI" },
    { "country": "Zambia", "name": "Proflight Commuter Services", "icao": "" },
    { "country": "Australia", "name": "Qantas", "icao": "QFA" },
    { "country": "Qatar", "name": "Qatar Airways", "icao": "QTR" },
    { "country": "Guatemala", "name": "RACSA", "icao": "" },
    { "country": "United Kingdom", "name": "Kinloss Flying Training Unit", "icao": "KIN" },
    { "country": "Morocco", "name": "Regional Airlines", "icao": "" },
    { "country": "Australia", "name": "Regional Express", "icao": "RXA" },
    { "country": "United States", "name": "Republic Airlines", "icao": "RPA" },
    { "country": "Indonesia", "name": "Republic Express Airlines", "icao": "RPH" },
    { "country": "Russia", "name": "Rossiya", "icao": "" },
    { "country": "Cook Islands", "name": "Air Rarotonga", "icao": "RAR" },
    { "country": "Morocco", "name": "Royal Air Maroc", "icao": "RAM" },
    { "country": "Brunei", "name": "Royal Brunei Airlines", "icao": "RBA" },
    { "country": "Jordan", "name": "Royal Jordanian", "icao": "RJA" },
    { "country": "Nepal", "name": "Royal Nepal Airlines", "icao": "RNA" },
    { "country": "Cambodia", "name": "Royal Phnom Penh Airways", "icao": "PPW" },
    { "country": "Russia", "name": "Rusline", "icao": "RLU" },
    { "country": "Rwanda", "name": "Rwandair Express", "icao": "RWD" },
    { "country": "United States", "name": "Ryan Air Services", "icao": "RYA" },
    { "country": "United States", "name": "Ryan International Airlines", "icao": "RYN" },
    { "country": "Ireland", "name": "Ryanair", "icao": "RYR" },
    { "country": "France", "name": "Régional", "icao": "RAE" },
    { "country": "Portugal", "name": "SATA International", "icao": "RZO" },
    { "country": "South Africa", "name": "South African Airways", "icao": "SAA" },
    { "country": "Pakistan", "name": "Shaheen Air International", "icao": "SAI" },
    { "country": "Sweden", "name": "Scandinavian Airlines System", "icao": "SAS" },
    { "country": "United Kingdom", "name": "ScotAirways", "icao": "SAY" },
    { "country": "Russia", "name": "S7 Airlines", "icao": "SBI" },
    { "country": "United States", "name": "Seaborne Airlines", "icao": "SBS" },
    { "country": "United States", "name": "Scenic Airlines", "icao": "SCE" },
    { "country": "Sri Lanka", "name": "SriLankan Airlines", "icao": "ALK" },
    { "country": "United States", "name": "Sun Country Airlines", "icao": "SCX" },
    { "country": "United States", "name": "Southeast Air", "icao": "SEA" },
    { "country": "Greece", "name": "Sky Express", "icao": "SEH" },
    { "country": "India", "name": "Spicejet", "icao": "SEJ" },
    { "country": "Japan", "name": "Star Flyer", "icao": "SFJ" },
    { "country": "United States", "name": "Skagway Air Service", "icao": "SGY" },
    { "country": "Algeria", "name": "Sahara Airlines", "icao": "SHD" },
    { "country": "Portugal", "name": "SATA Air Acores", "icao": "SAT" },
    { "country": "Singapore", "name": "Singapore Airlines", "icao": "SIA" },
    { "country": "Russia", "name": "Sibaviatrans", "icao": "SIB" },
    { "country": "Ireland", "name": "Skynet Airlines", "icao": "SIH" },
    { "country": "Indonesia", "name": "Sriwijaya Air", "icao": "SJY" },
    { "country": "Saudi Arabia", "name": "Sama Airlines", "icao": "SMY" },
    { "country": "Singapore", "name": "Singapore Airlines Cargo", "icao": "SQC" },
    { "country": "Cambodia", "name": "Siem Reap Airways", "icao": "SRH" },
    { "country": "Philippines", "name": "South East Asian Airlines", "icao": "SRQ" },
    { "country": "Canada", "name": "Skyservice Airlines", "icao": "SSV" },
    { "country": "Argentina", "name": "Servicios de Transportes A", "icao": "STU" },
    { "country": "Sudan", "name": "Sudan Airways", "icao": "SUD" },
    { "country": "Saudi Arabia", "name": "Saudi Arabian Airlines", "icao": "SVA" },
    { "country": "United States", "name": "Southwest Airlines", "icao": "SWA" },
    { "country": "Argentina", "name": "Southern Winds Airlines", "icao": "SWD" },
    { "country": "Switzerland", "name": "Swiss International Air Lines", "icao": "SWR" },
    { "country": "Switzerland", "name": "Swissair", "icao": "SWR" },
    { "country": "Switzerland", "name": "Swiss European Air Lines", "icao": "SWU" },
    { "country": "Sweden", "name": "Swe Fly", "icao": "SWV" },
    { "country": "Turkey", "name": "SunExpress", "icao": "SXS" },
    { "country": "Syrian Arab Republic", "name": "Syrian Arab Airlines", "icao": "SYR" },
    { "country": "United States", "name": "Skywalk Airlines", "icao": "SYX" },
    { "country": "China", "name": "Shandong Airlines", "icao": "CDG" },
    { "country": "Norway", "name": "SAS Braathens", "icao": "CNO" },
    { "country": "China", "name": "Spring Airlines", "icao": "CQH" },
    { "country": "China", "name": "Sichuan Airlines", "icao": "CSC" },
    { "country": "China", "name": "Shanghai Airlines", "icao": "CSH" },
    { "country": "China", "name": "Shenzhen Airlines", "icao": "CSZ" },
    { "country": "Israel", "name": "Sun D'Or", "icao": "ERO" },
    { "country": "Slovakia", "name": "SkyEurope", "icao": "ESK" },
    { "country": "Slovakia", "name": "Sky Europe Airlines", "icao": "HSK" },
    { "country": "Spain", "name": "Spanair", "icao": "JKK" },
    { "country": "United States", "name": "Spirit Airlines", "icao": "NKS" },
    { "country": "Colombia", "name": "SATENA", "icao": "NSE" },
    { "country": "Australia", "name": "Skywest Airlines", "icao": "OZW" },
    { "country": "Venezuela", "name": "Santa Barbara Airlines", "icao": "BBR" },
    { "country": "Chile", "name": "Sky Airline", "icao": "SKU" },
    { "country": "United States", "name": "SkyWest", "icao": "SKW" },
    { "country": "Sweden", "name": "Skyways Express", "icao": "SKX" },
    { "country": "Japan", "name": "Skymark Airlines", "icao": "SKY" },
    { "country": "Singapore", "name": "SilkAir", "icao": "SLK" },
    { "country": "Suriname", "name": "Surinam Airways", "icao": "SLM" },
    { "country": "Denmark", "name": "Sterling Airlines", "icao": "SNB" },
    { "country": "Japan", "name": "Skynet Asia Airways", "icao": "SNJ" },
    { "country": "Solomon Islands", "name": "Solomon Airlines", "icao": "SOL" },
    { "country": "United States", "name": "Southern Airways", "icao": "SOU" },
    { "country": "Russia", "name": "Saratov Aviation Division", "icao": "SOV" },
    { "country": "Kazakhstan", "name": "Sat Airlines", "icao": "SOZ" },
    { "country": "United States", "name": "South Pacific Island Airways", "icao": "SPI" },
    { "country": "United States", "name": "Shuttle America", "icao": "TCF" },
    { "country": "Kazakhstan", "name": "Scat Air", "icao": "VSV" },
    { "country": "Ecuador", "name": "TAME", "icao": "TAE" },
    { "country": "Brazil", "name": "TAM Brazilian Airlines", "icao": "TAM" },
    { "country": "Portugal", "name": "TAP Portugal", "icao": "TAP" },
    { "country": "Tunisia", "name": "Tunisair", "icao": "TAR" },
    { "country": "Thailand", "name": "Thai Air Cargo", "icao": "TCG" },
    { "country": "Belgium", "name": "Thomas Cook Airlines", "icao": "TCW" },
    { "country": "United Kingdom", "name": "Thomas Cook Airlines", "icao": "TCX" },
    { "country": "Indonesia", "name": "Trigana Air Service", "icao": "TGN" },
    { "country": "Singapore", "name": "Tiger Airways", "icao": "TGW" },
    { "country": "Australia", "name": "Tigerair Australia", "icao": "TGG" },
    { "country": "Thailand", "name": "Thai Airways International", "icao": "THA" },
    { "country": "Turkey", "name": "Turk Hava Kurumu Hava Taksi Isletmesi", "icao": "THK" },
    { "country": "Thailand", "name": "Thai AirAsia", "icao": "AIQ" },
    { "country": "Turkey", "name": "Turkish Airlines", "icao": "THY" },
    { "country": "Tajikistan", "name": "Tajikistan International Airlines", "icao": "TIL" },
    { "country": "France", "name": "Twin Jet", "icao": "TJT" },
    { "country": "Ireland", "name": "Translift Airways", "icao": "TLA" },
    { "country": "Lebanon", "name": "Trans Mediterranean Airlines", "icao": "TMA" },
    { "country": "Aruba", "name": "Tiara Air", "icao": "TNM" },
    { "country": "United Kingdom", "name": "Thomsonfly", "icao": "TOM" },
    { "country": "Belize", "name": "Tropic Air", "icao": "TOS" },
    { "country": "Colombia", "name": "TAMPA", "icao": "TPA" },
    { "country": "Taiwan", "name": "TransAsia Airways", "icao": "TNA" },
    { "country": "Netherlands", "name": "Transavia Holland", "icao": "TRA" },
    { "country": "Portugal", "name": "TACV", "icao": "TCV" },
    { "country": "Canada", "name": "Transwest Air", "icao": "ABS" },
    { "country": "Russia", "name": "Transaero Airlines", "icao": "TSO" },
    { "country": "Turkmenistan", "name": "Turkmenistan Airlines", "icao": "TUA" },
    { "country": "Tunisia", "name": "Tuninter", "icao": "TUI" },
    { "country": "Czech Republic", "name": "Travel Service", "icao": "TVS" },
    { "country": "Sweden", "name": "TUIfly Nordic", "icao": "BLX" },
    { "country": "Angola", "name": "TAAG Angola Airlines", "icao": "DTA" },
    { "country": "Turkey", "name": "Turkish Air Force", "icao": "HVK" },
    { "country": "Paraguay", "name": "TAM Mercosur", "icao": "LAP" },
    { "country": "United States", "name": "Trans States Airlines", "icao": "LOF" },
    { "country": "Romania", "name": "Tarom", "icao": "ROT" },
    { "country": "Azerbaijan", "name": "Turan Air", "icao": "URN" },
    { "country": "Brazil", "name": "TRIP Linhas A", "icao": "TIB" },
    { "country": "United States", "name": "USA3000 Airlines", "icao": "GWY" },
    { "country": "United States", "name": "United Airlines", "icao": "UAL" },
    { "country": "Zimbabwe", "name": "United Air Charters", "icao": "UAC" },
    { "country": "Russia", "name": "Ural Airlines", "icao": "SVR" },
    { "country": "Ukraine", "name": "UM Airlines", "icao": "UKM" },
    { "country": "United States", "name": "US Airways", "icao": "USA" },
    { "country": "United States", "name": "US Helicopter", "icao": "USH" },
    { "country": "Russia", "name": "UTair Aviation", "icao": "UTA" },
    { "country": "United States", "name": "United States Air Force", "icao": "AIO" },
    { "country": "Uzbekistan", "name": "Uzbekistan Airways", "icao": "UZB" },
    { "country": "Ukraine", "name": "Ukraine International Airlines", "icao": "AUI" },
    { "country": "United States", "name": "US Helicopter Corporation", "icao": "" },
    { "country": "Singapore", "name": "Valuair", "icao": "VLU" },
    { "country": "Vietnam", "name": "Vasco Air", "icao": "VFC" },
    { "country": "Vietnam", "name": "Vietnam Airlines", "icao": "HVN" },
    { "country": "Russia", "name": "VIM Airlines", "icao": "MOV" },
    { "country": "Mexico", "name": "Volaris", "icao": "VOI" },
    { "country": "Russia", "name": "Volga-Dnepr Airlines", "icao": "VDA" },
    { "country": "United States", "name": "Virgin America", "icao": "VRD" },
    { "country": "Belgium", "name": "Virgin Express", "icao": "VEX" },
    { "country": "Nigeria", "name": "Virgin Nigeria Airways", "icao": "VGN" },
    { "country": "United Kingdom", "name": "Virgin Atlantic Airways", "icao": "VIR" },
    { "country": "Macao", "name": "Viva Macau", "icao": "VVM" },
    { "country": "Italy", "name": "Volare Airlines", "icao": "VLE" },
    { "country": "Spain", "name": "Vueling Airlines", "icao": "VLG" },
    { "country": "Russia", "name": "Vladivostok Air", "icao": "VLK" },
    { "country": "Brazil", "name": "Varig Log", "icao": "VLO" },
    { "country": "Australia", "name": "Virgin Australia", "icao": "VOZ" },
    { "country": "Brazil", "name": "VRG Linhas Aereas", "icao": "VRN" },
    { "country": "Brazil", "name": "VASP", "icao": "VSP" },
    { "country": "Belgium", "name": "VLM Airlines", "icao": "VLM" },
    { "country": "Peru", "name": "Wayraper", "icao": "" },
    { "country": "Brazil", "name": "WebJet Linhas A", "icao": "WEB" },
    { "country": "Austria", "name": "Welcome Air", "icao": "WLC" },
    { "country": "Canada", "name": "West Coast Air", "icao": "" },
    { "country": "Canada", "name": "WestJet", "icao": "WJA" },
    { "country": "United States", "name": "Western Airlines", "icao": "WAL" },
    { "country": "Norway", "name": "Widerøe", "icao": "WIF" },
    { "country": "Italy", "name": "Wind Jet", "icao": "JET" },
    { "country": "Indonesia", "name": "Wings Air", "icao": "WON" },
    { "country": "Hungary", "name": "Wizz Air", "icao": "WZZ" },
    { "country": "Bulgaria", "name": "Wizz Air Hungary", "icao": "WVL" },
    { "country": "United States", "name": "World Airways", "icao": "WOA" },
    { "country": "France", "name": "XL Airways France", "icao": "SEU" },
    { "country": "China", "name": "Xiamen Airlines", "icao": "CXA" },
    { "country": "Russia", "name": "Yamal Airlines", "icao": "LLM" },
    { "country": "Yemen", "name": "Yemenia", "icao": "IYE" },
    { "country": "Ukraine", "name": "Yuzhmashavia", "icao": "UMK" },
    { "country": "Tanzania", "name": "Zanair", "icao": "TAN" },
    { "country": "Canada", "name": "Zoom Airlines", "icao": "OOM" },
    { "country": "\\N", "name": "Tyrolean Airways", "icao": "TYR" },
    { "country": "Maldives", "name": "Maldivian Air Taxi", "icao": "\\N" },
    { "country": "Cambodia", "name": "Royal Air Cambodge", "icao": "RAC" },
    { "country": "Burma", "name": "Air Mandalay", "icao": "\\N" },
    { "country": "\\N", "name": "Unknown", "icao": "N/A" },
    { "country": "Republic of Korea", "name": "Air Busan", "icao": "ABL" },
    { "country": "Russia", "name": "Sky Express", "icao": "SXR" },
    { "country": "Russia", "name": "Globus", "icao": "GLP" },
    { "country": "Kazakhstan", "name": "Air Kazakhstan", "icao": "KZK" },
    { "country": "Japan", "name": "Japan Air System", "icao": "JAS" },
    { "country": "Switzerland", "name": "EasyJet (DS)", "icao": "\\N" },
    { "country": "Peru", "name": "Star Peru (2I)", "icao": "\\N" },
    { "country": "United States", "name": "Carnival Air Lines", "icao": "\\N" },
    { "country": "Bangladesh", "name": "United Airways", "icao": "UBD" },
    { "country": "Kenya", "name": "Fly540", "icao": "FFV" },
    { "country": "France", "name": "Transavia France", "icao": "TVF" },
    { "country": "United States", "name": "Island Air (WP)", "icao": "MKU" },
    { "country": "Taiwan", "name": "Uni Air", "icao": "UIA" },
    { "country": "Belarus", "name": "Gomelavia", "icao": "\\N" },
    { "country": "Russia", "name": "Red Wings", "icao": "RWZ" },
    { "country": "Germany", "name": "TUIfly (X3)", "icao": "\\N" },
    { "country": "Yemen", "name": "Felix Airways", "icao": "FXX" },
    { "country": "Russia", "name": "Kostromskie avialinii", "icao": "KOQ" },
    { "country": "Spain", "name": "Greenfly", "icao": "GFY" },
    { "country": "Tajikistan", "name": "Tajik Air", "icao": "\\N" },
    { "country": "Mozambique", "name": "Air Mozambique", "icao": "\\N" },
    { "country": "Estonia", "name": "ELK Airways", "icao": "ELK" },
    { "country": "Gabon", "name": "Gabon Airlines", "icao": "GBK" },
    { "country": "Sweden", "name": "MCA Airlines", "icao": "MCA" },
    { "country": "Maldives", "name": "Maldivo Airlines", "icao": "MAV" },
    { "country": "Fiji", "name": "Virgin Pacific", "icao": "VNP" },
    { "country": "Philippines", "name": "Zest Air", "icao": "\\N" },
    { "country": "Burma", "name": "Yangon Airways", "icao": "\\N" },
    { "country": "South Korea", "name": "Eastar Jet", "icao": "ESR" },
    { "country": "South Korea", "name": "Jin Air", "icao": "JNA" },
    { "country": "Kuwait", "name": "Wataniya Airways", "icao": "KW1" },
    { "country": "Morocco", "name": "Air Arabia Maroc", "icao": "\\N" },
    { "country": "Latvia", "name": "Baltic Air lines", "icao": "BA1" },
    { "country": "Canada", "name": "Ciel Canadien", "icao": "YCC" },
    { "country": "Canada", "name": "Canadian National Airways", "icao": "YCP" },
    { "country": "United States", "name": "Epic Holiday", "icao": "4AA" },
    { "country": "Vietnam", "name": "Indochina Airlines", "icao": "AXC" },
    { "country": "Chile", "name": "Air Comet Chile", "icao": "\\N" },
    { "country": "Germany", "name": "German Air Force - FLB", "icao": "FLB" },
    { "country": "Germany", "name": "Line Blue", "icao": "LBL" },
    { "country": "Lithuania", "name": "FlyLAL Charters", "icao": "LLC" },
    { "country": "Austria", "name": "Salzburg arrows", "icao": "\\N" },
    { "country": "United States", "name": "Texas Wings", "icao": "TXW" },
    { "country": "Israel", "name": "Dennis Sky", "icao": "DSY" },
    { "country": "Belgium", "name": "Zz", "icao": "\\N" },
    { "country": "United States", "name": "Atifly", "icao": "A1F" },
    { "country": "Dominican Republic", "name": "Aerolineas heredas santa maria", "icao": "SZB" },
    { "country": "Italy", "name": "Ciao Air", "icao": "\\N" },
    { "country": "United Kingdom", "name": "Jc royal.britannica", "icao": "JRB" },
    { "country": "Chile", "name": "Pal airlines", "icao": "\\N" },
    { "country": "Canada", "name": "CanXpress", "icao": "CA1" },
    { "country": "Slovakia", "name": "Danube Wings (V5)", "icao": "\\N" },
    { "country": "Australia", "name": "Sharp Airlines", "icao": "SHA" },
    { "country": "Canada", "name": "CanXplorer", "icao": "CAP" },
    { "country": "Mexico", "name": "Click (Mexicana)", "icao": "\\N" },
    { "country": "Canada", "name": "World Experience Airline", "icao": "WE1" },
    { "country": "Russia", "name": "ALAK", "icao": "\\N" },
    { "country": "United States", "name": "Air Choice One", "icao": "\\N" },
    { "country": "China", "name": "Tianjin Airlines", "icao": "GCR" },
    { "country": "China", "name": "China United", "icao": "\\N" },
    { "country": "United States", "name": "Locair", "icao": "LOC" },
    { "country": "Afghanistan", "name": "Safi Airlines", "icao": "\\N" },
    { "country": "United States", "name": "SeaPort Airlines", "icao": "SQH" },
    { "country": "United States", "name": "Salmon Air", "icao": "\\N" },
    { "country": "Germany", "name": "Bobb Air Freight", "icao": "\\N" },
    { "country": "Lithuania", "name": "Star1 Airlines", "icao": "HCW" },
    { "country": "Indonesia", "name": "Pelita", "icao": "\\N" },
    { "country": "United States", "name": "Alaska Seaplane Service", "icao": "\\N" },
    { "country": "Canada", "name": "Enerjet", "icao": "ENJ" },
    { "country": "Mexico", "name": "MexicanaLink", "icao": "MXI" },
    { "country": "Iceland", "name": "Island Spirit", "icao": "ISX" },
    { "country": "Peru", "name": "TACA Peru", "icao": "\\N" },
    { "country": "Portugal", "name": "Orbest", "icao": "OBS" },
    { "country": "Bahamas", "name": "Southern Air Charter", "icao": "SOA" },
    { "country": "Saint Vincent and the Grenadines", "name": "SVG Air", "icao": "SVG" },
    { "country": "Dominican Republic", "name": "Air Century", "icao": "CEY" },
    { "country": "Dominican Republic", "name": "Pan Am World Airways Dominicana", "icao": "\\N" },
    { "country": "Iceland", "name": "Primera Air", "icao": "\\N" },
    { "country": "Guadeloupe", "name": "Air Antilles Express", "icao": "\\N" },
    { "country": "Argentina", "name": "Sol Lineas Aereas", "icao": "OLS" },
    { "country": "Paraguay", "name": "Regional Paraguaya", "icao": "REP" },
    { "country": "Ecuador", "name": "VIP Ecuador", "icao": "\\N" },
    { "country": "Peru", "name": "Transportes Aereos Cielos Andinos", "icao": "NDN" },
    { "country": "Peru", "name": "Peruvian Airlines", "icao": "\\N" },
    { "country": "Colombia", "name": "EasyFly", "icao": "EFY" },
    { "country": "Russia", "name": "Polar Airlines", "icao": "\\N" },
    { "country": "Mauritius", "name": "Catovair", "icao": "\\N" },
    { "country": "Spain", "name": "Andalus Lineas Aereas", "icao": "ANU" },
    { "country": "Angola", "name": "Air 26", "icao": "DCD" },
    { "country": "Mauritania", "name": "Mauritania Airways", "icao": "MTW" },
    { "country": "Equatorial Guinea", "name": "CEIBA Intercontinental", "icao": "CEL" },
    { "country": "Cape Verde", "name": "Halcyonair", "icao": "\\N" },
    { "country": "Congo (Kinshasa)", "name": "Business Aviation", "icao": "\\N" },
    { "country": "Congo (Kinshasa)", "name": "Compagnie Africaine d'Aviation", "icao": "\\N" },
    { "country": "Zambia", "name": "Zambia Skyways", "icao": "\\N" },
    { "country": "Egypt", "name": "AlMasria Universal Airlines", "icao": "LMU" },
    { "country": "Egypt", "name": "EgyptAir Express", "icao": "MSE" },
    { "country": "Latvia", "name": "SmartLynx Airlines", "icao": "\\N" },
    { "country": "Egypt", "name": "Air Italy Egypt", "icao": "EUD" },
    { "country": "Egypt", "name": "KoralBlue Airlines", "icao": "KBR" },
    { "country": "Ukraine", "name": "Wind Rose Aviation", "icao": "WRC" },
    { "country": "Cameroon", "name": "Elysian Airlines", "icao": "GIE" },
    { "country": "Tunisia", "name": "Sevenair", "icao": "SEN" },
    { "country": "Greece", "name": "Hellenic Imperial Airways", "icao": "IMP" },
    { "country": "Netherlands", "name": "Amsterdam Airlines", "icao": "AAN" },
    { "country": "Niger", "name": "Arik Niger", "icao": "NAK" },
    { "country": "Nigeria", "name": "Dana Air", "icao": "\\N" },
    { "country": "Sao Tome and Principe", "name": "STP Airways", "icao": "STP" },
    { "country": "Lebanon", "name": "Med Airways", "icao": "\\N" },
    { "country": "Uganda", "name": "Skyjet Airlines", "icao": "SJU" },
    { "country": "Russia", "name": "Air Volga", "icao": "\\N" },
    { "country": "Denmark", "name": "Transavia Denmark", "icao": "TDK" },
    { "country": "Jordan", "name": "Royal Falcon", "icao": "RFJ" },
    { "country": "Georgia", "name": "Euroline", "icao": "MJX" },
    { "country": "Spain", "name": "Greenfly", "icao": "GFY" },
    { "country": "Tajikistan", "name": "Tajik Air", "icao": "\\N" },
    { "country": "Mozambique", "name": "Air Mozambique", "icao": "\\N" },
    { "country": "Estonia", "name": "ELK Airways", "icao": "ELK" },
    { "country": "Gabon", "name": "Gabon Airlines", "icao": "GBK" },
    { "country": "Sweden", "name": "MCA Airlines", "icao": "MCA" },
    { "country": "Maldives", "name": "Maldivo Airlines", "icao": "MAV" },
    { "country": "Fiji", "name": "Virgin Pacific", "icao": "VNP" },
    { "country": "Philippines", "name": "Zest Air", "icao": "\\N" },
    { "country": "Burma", "name": "Yangon Airways", "icao": "\\N" },
    { "country": "South Korea", "name": "Eastar Jet", "icao": "ESR" },
    { "country": "South Korea", "name": "Jin Air", "icao": "JNA" },
    { "country": "Kuwait", "name": "Wataniya Airways", "icao": "KW1" },
    { "country": "Morocco", "name": "Air Arabia Maroc", "icao": "\\N" },
    { "country": "Latvia", "name": "Baltic Air lines", "icao": "BA1" },
    { "country": "Canada", "name": "Ciel Canadien", "icao": "YCC" },
    { "country": "Canada", "name": "Canadian National Airways", "icao": "YCP" },
    { "country": "United States", "name": "Epic Holiday", "icao": "4AA" },
    { "country": "Vietnam", "name": "Indochina Airlines", "icao": "AXC" },
    { "country": "Chile", "name": "Air Comet Chile", "icao": "\\N" },
    { "country": "Germany", "name": "German Air Force - FLB", "icao": "FLB" },
    { "country": "Germany", "name": "Line Blue", "icao": "LBL" },
    { "country": "Lithuania", "name": "FlyLAL Charters", "icao": "LLC" },
    { "country": "Austria", "name": "Salzburg arrows", "icao": "\\N" },
    { "country": "United States", "name": "Texas Wings", "icao": "TXW" },
    { "country": "Israel", "name": "Dennis Sky", "icao": "DSY" },
    { "country": "Belgium", "name": "Zz", "icao": "\\N" },
    { "country": "United States", "name": "Atifly", "icao": "A1F" },
    { "country": "Dominican Republic", "name": "Aerolineas heredas santa maria", "icao": "SZB" },
    { "country": "Italy", "name": "Ciao Air", "icao": "\\N" },
    { "country": "United Kingdom", "name": "Jc royal.britannica", "icao": "JRB" },
    { "country": "Chile", "name": "Pal airlines", "icao": "\\N" },
    { "country": "Canada", "name": "CanXpress", "icao": "CA1" },
    { "country": "Slovakia", "name": "Danube Wings (V5)", "icao": "\\N" },
    { "country": "Australia", "name": "Sharp Airlines", "icao": "SHA" },
    { "country": "Canada", "name": "CanXplorer", "icao": "CAP" },
    { "country": "Mexico", "name": "Click (Mexicana)", "icao": "\\N" },
    { "country": "Canada", "name": "World Experience Airline", "icao": "WE1" },
    { "country": "Russia", "name": "ALAK", "icao": "\\N" },
    { "country": "United States", "name": "Air Choice One", "icao": "\\N" },
    { "country": "China", "name": "Tianjin Airlines", "icao": "GCR" },
    { "country": "China", "name": "China United", "icao": "\\N" },
    { "country": "United States", "name": "Locair", "icao": "LOC" },
    { "country": "Afghanistan", "name": "Safi Airlines", "icao": "\\N" },
    { "country": "United States", "name": "SeaPort Airlines", "icao": "SQH" },
    { "country": "United States", "name": "Salmon Air", "icao": "\\N" },
    { "country": "Germany", "name": "Bobb Air Freight", "icao": "\\N" },
    { "country": "Lithuania", "name": "Star1 Airlines", "icao": "HCW" },
    { "country": "Indonesia", "name": "Pelita", "icao": "\\N" },
    { "country": "United States", "name": "Alaska Seaplane Service", "icao": "\\N" },
    { "country": "Canada", "name": "Enerjet", "icao": "ENJ" },
    { "country": "Mexico", "name": "MexicanaLink", "icao": "MXI" },
    { "country": "United States", "name": "Caribbean Sun Airlines", "icao": "RSU" },
    { "country": "United States", "name": "Champion Air", "icao": "\\N" },
    { "country": "United States", "name": "Frontier Flying Service", "icao": "FTA" },
    { "country": "United States", "name": "Big Island Air", "icao": "\\N" },
    { "country": "United States", "name": "USA Jet Airlines", "icao": "\\N" },
    { "country": "United States", "name": "Aloha Air Cargo", "icao": "\\N" },
    { "country": "United States", "name": "Inter Island Airways", "icao": "WSH" },
    { "country": "China", "name": "Joy Air", "icao": "JOY" },
    { "country": "India", "name": "Air India Regional", "icao": "\\N" },
    { "country": "India", "name": "MDLR Airlines", "icao": "\\N" },
    { "country": "India", "name": "Jagson Airlines", "icao": "JGN" },
    { "country": "Maldives", "name": "Maldivian", "icao": "\\N" },
    { "country": "Indonesia", "name": "Xpressair", "icao": "\\N" },
    { "country": "Australia", "name": "Strategic Airlines", "icao": "\\N" },
    { "country": "Iran", "name": "Fars Air Qeshm", "icao": "QFZ" },
    { "country": "Kyrgyzstan", "name": "Eastok Avia", "icao": "EAA" },
    { "country": "United Arab Emirates", "name": "Jupiter Airlines", "icao": "JPU" },
    { "country": "Pakistan", "name": "Vision Air International", "icao": "VIS" },
    { "country": "Iraq", "name": "Al-Naser Airlines", "icao": "\\N" },
    { "country": "Japan", "name": "Fuji Dream Airlines", "icao": "\\N" },
    { "country": "South Korea", "name": "Korea Express Air", "icao": "KEA" },
    { "country": "Mongolia", "name": "Eznis Airways", "icao": "EZA" },
    { "country": "Palau", "name": "Pacific Flier", "icao": "PFL" },
    { "country": "Syria", "name": "Syrian Pearl Airlines", "icao": "PSB" },
    { "country": "Thailand", "name": "SGA Airlines", "icao": "\\N" },
    { "country": "New Zealand", "name": "Air2there", "icao": "\\N" },
    { "country": "Russia", "name": "Avianova (Russia)", "icao": "\\N" },
    { "country": "Iran", "name": "Parmiss Airlines (IPV)", "icao": "IPV" },
    { "country": "Germany", "name": "EuropeSky", "icao": "EUV" },
    { "country": "Brazil", "name": "BRAZIL AIR", "icao": "BZE" },
    { "country": "Germany", "name": "Homer Air", "icao": "OME" },
    { "country": "United States", "name": "U.S. Air", "icao": "--+" },
    { "country": "Australia", "name": "Jayrow", "icao": "\\N" },
    { "country": "Australia", "name": "Wilderness Air", "icao": "\\N" },
    { "country": "Australia", "name": "Whitaker Air", "icao": "\\N" },
    { "country": "United States", "name": "PanAm World Airways", "icao": "PQW" },
    { "country": "Germany", "name": "Virginwings", "icao": "VWA" },
    { "country": "Greece", "name": "KSY", "icao": "KSY" },
    { "country": "Uruguay", "name": "Buquebus Líneas Aéreas", "icao": "BQB" },
    { "country": "Russia", "name": "SOCHI AIR", "icao": "KOL" },
    { "country": "Ukraine", "name": "Wizz Air Ukraine", "icao": "WAU" },
    { "country": "Cyprus", "name": "88", "icao": "VVN" },
    { "country": "Russia", "name": "LCM AIRLINES", "icao": "LMM" },
    { "country": "Cambodia", "name": "Cambodia Angkor Air (K6)", "icao": "\\N" },
    { "country": "United Kingdom", "name": "Royal European Airlines", "icao": "\\N" },
    { "country": "France", "name": "Tom's & co airliners", "icao": "T&O" },
    { "country": "Brazil", "name": "Azul", "icao": "AZU" },
    { "country": "Russia", "name": "LSM Airlines", "icao": "LOO" },
    { "country": "Russia", "name": "Zapolyarie Airlines", "icao": "PZY" },
    { "country": "Finland", "name": "Finlandian", "icao": "FN1" },
    { "country": "Cameroon", "name": "LionXpress", "icao": "LIX" },
    { "country": "Pakistan", "name": "Genesis", "icao": "\\N" },
    { "country": "Congo (Kinshasa)", "name": "Congo Express", "icao": "\\N" },
    { "country": "United Arab Emirates", "name": "Fly Dubai", "icao": "FDB" },
    { "country": "Dominican Republic", "name": "Domenican Airlines", "icao": "MDO" },
    { "country": "Austria", "name": "ConneX European Airline", "icao": "2CO" },
    { "country": "Italy", "name": "Aereonautica militare", "icao": "AXZ" },
    { "country": "Indonesia", "name": "Kal Star Aviation", "icao": "KLS" },
    { "country": "Russia", "name": "LSM AIRLINES ", "icao": "YZZ" },
    { "country": "Russia", "name": "UTair-Express", "icao": "\\N" },
    { "country": "China", "name": "Huaxia", "icao": "\\N" },
    { "country": "Russia", "name": "Zabaykalskii Airlines", "icao": "ZZZ" },
    { "country": "United States", "name": "CBM America", "icao": "XBM" },
    { "country": "Russia", "name": "Marysya Airlines", "icao": "1QA" },
    { "country": "Peru", "name": "N1", "icao": "\\N" },
    { "country": "South Africa", "name": "Airlink ()", "icao": "\\N" },
    { "country": "Germany", "name": "Westfalia Express VA", "icao": "WFX" },
    { "country": "Czech Republic", "name": "JobAir", "icao": "\\N" },
    { "country": "United States", "name": "Black Stallion Airways", "icao": "BSA" },
    { "country": "Germany", "name": "German International Air Lines", "icao": "GER" },
    { "country": "Brazil", "name": "TrasBrasil", "icao": "TBZ" },
    { "country": "Brazil", "name": "TransBrasil Airlines", "icao": "THS" },
    { "country": "China", "name": "China SSS", "icao": "\\N" },
    { "country": "Vietnam", "name": "AIR INDOCHINE", "icao": "IIA" },
    { "country": "Thailand", "name": "Happy Air", "icao": "HPY" },
    { "country": "Thailand", "name": "Solar Air", "icao": "SRB" },
    { "country": "Vietnam", "name": "Air Mekong", "icao": "MKG" },
    { "country": "Canada", "name": "Harbour Air (Priv)", "icao": "\\N" },
    { "country": "Germany", "name": "Air Hamburg (AHO)", "icao": "AHO" },
    { "country": "Russia", "name": "ZABAIKAL AIRLINES", "icao": "ZTT" },
    { "country": "Brazil", "name": "TransHolding", "icao": "THI" },
    { "country": "Argentina", "name": "SUR Lineas Aereas", "icao": "SZZ" },
    { "country": "Guinea", "name": "Aerolineas Africanas", "icao": "AA1" },
    { "country": "Nepal", "name": "Yeti Airways", "icao": "\\N" },
    { "country": "United States", "name": "Yellowstone Club Private Shuttle", "icao": "\\N" },
    { "country": "Georgia", "name": "Caucasus Airlines", "icao": "\\N" },
    { "country": "Serbia", "name": "Serbian Airlines", "icao": "SA1" },
    { "country": "Netherlands Antilles", "name": "Windward Islands Airways", "icao": "\\N" },
    { "country": "Brazil", "name": "TransHolding System", "icao": "TYS" },
    { "country": "Colombia", "name": "CCML Airlines", "icao": "CCC" },
    { "country": "Lithuania", "name": "Small Plane Airlines", "icao": "ELC" },
    { "country": "Brazil", "name": "Fly Brasil", "icao": "FBL" },
    { "country": "United Kingdom", "name": "CB Airways UK ( Interliging Flights )", "icao": "CIF" },
    { "country": "Colombia", "name": "Fly Colombia ( Interliging Flights )", "icao": "3FF" },
    { "country": "United States", "name": "Trans Pas Air", "icao": "TP6" },
    { "country": "Russia", "name": "KMV", "icao": "\\N" },
    { "country": "Nepal", "name": "Himalayan Airlines", "icao": "HYM" },
    { "country": "India", "name": "Indya Airline Group", "icao": "IG1" },
    { "country": "Canada", "name": "Sunwing", "icao": "\\N" },
    { "country": "Turkey", "name": "Turkish Wings Domestic", "icao": "TWD" },
    { "country": "Japan", "name": "Japan Regio", "icao": "ZXY" },
    { "country": "India", "name": "OCEAN AIR CARGO", "icao": "IXO" },
    { "country": "Argentina", "name": "Norte Lineas Aereas", "icao": "\\N" },
    { "country": "Brazil", "name": "Austral Brasil", "icao": "\\N" },
    { "country": "Turkey", "name": "PEGASUS AIRLINES-", "icao": "\\N" },
    { "country": "Kyrgyzstan", "name": "Nihon.jet connect", "icao": "NX1" },
    { "country": "Cameroon", "name": "Camair-co", "icao": "\\N" },
    { "country": "Canada", "name": "Sky Regional", "icao": "\\N" },
    { "country": "Russia", "name": "LSM International ", "icao": "UWW" },
    { "country": "American Samoa", "name": "Baikotovitchestrian Airlines ", "icao": "BUU" },
    { "country": "Russia", "name": "Luchsh Airlines ", "icao": "LJJ" },
    { "country": "Poland", "name": "ENTERair", "icao": "QQQ" },
    { "country": "Germany", "name": "Air Cargo Germany", "icao": "\\N" },
    { "country": "Mongolia", "name": "Mongolian International Air Lines ", "icao": "ZTF" },
    { "country": "South Korea", "name": "Tway Airlines", "icao": "TWB" },
    { "country": "United States", "name": "Papillon Grand Canyon Helicopters", "icao": "\\N" },
    { "country": "Egypt", "name": "Jusur airways", "icao": "JSR" },
    { "country": "Brazil", "name": "NEXT Brasil", "icao": "NXB" },
    { "country": "Russia", "name": "AeroWorld ", "icao": "WER" },
    { "country": "Brazil", "name": "GNB Linhas Aereas", "icao": "\\N" },
    { "country": "United States", "name": "Usa Sky Cargo", "icao": "ES2" },
    { "country": "South Korea", "name": "Hankook Airline", "icao": "HNX" },
    { "country": "Barbados", "name": "REDjet", "icao": "\\N" },
    { "country": "Peru", "name": "Red Jet Andes", "icao": "\\N" },
    { "country": "Canada", "name": "Red Jet Canada", "icao": "\\N" },
    { "country": "Poland", "name": "Sprintair", "icao": "SAR" },
    { "country": "Mexico", "name": "Red Jet Mexico", "icao": "\\N" },
    { "country": "Russia", "name": "Marusya Airways", "icao": "MRS" },
    { "country": "United States", "name": "Era Alaska", "icao": "ERR" },
    { "country": "Russia", "name": "AirRussia", "icao": "RRJ" },
    { "country": "United States", "name": "Hankook Air US", "icao": "HA1" },
    { "country": "Romania", "name": "Carpatair Flight Training", "icao": "SMW" },
    { "country": "Russia", "name": "I-Fly", "icao": "RSY" },
    { "country": "Brazil", "name": "Whitejets", "icao": "WTJ" },
    { "country": "France", "name": "VickJet", "icao": "VKJ" },
    { "country": "British Virgin Islands", "name": "BVI Airways", "icao": "\\N" },
    { "country": "Germany", "name": "Hamburg Airways", "icao": "HAY" },
    { "country": "Haiti", "name": "Salsa d'Haiti", "icao": "SLC" },
    { "country": "Zambia", "name": "Zambezi Airlines (ZMA)", "icao": "\\N" },
    { "country": "Thailand", "name": "Kan Air", "icao": "KND" },
    { "country": "United Kingdom", "name": "Air Cudlua", "icao": "CUD" },
    { "country": "Russia", "name": "Polet Airlines (Priv)", "icao": "\\N" },
    { "country": "Slovakia", "name": "Air Explore", "icao": "AXE" },
    { "country": "India", "name": "12 North", "icao": "N12" },
    { "country": "Czech Republic", "name": "Holidays Czech Airlines", "icao": "HCC" },
    { "country": "Austria", "name": "Comtel Air", "icao": "COE" },
    { "country": "Spain", "name": "Mint Airways", "icao": "MIC" },
    { "country": "United States", "name": "Orbit Airlines", "icao": "OBT" },
    { "country": "Romania", "name": "Air Bucharest", "icao": "BUR" },
    { "country": "Spain", "name": "AlbaStar", "icao": "LAV" },
    { "country": "Mauritania", "name": "Mauritania Airlines International", "icao": "MAI" },
    { "country": "Macedonia", "name": "MAT Airways", "icao": "MKD" },
    { "country": "Burma", "name": "Asian Wings Airways", "icao": "AWM" },
    { "country": "Egypt", "name": "Air Arabia Egypt", "icao": "RBG" },
    { "country": "Italy", "name": "Eagles Airlines", "icao": "EGS" },
    { "country": "Poland", "name": "YES Airways", "icao": "YEP" },
    { "country": "Italy", "name": "Alitalia Cityliner", "icao": "\\N" },
    { "country": "Romania", "name": "Direct Aero Services", "icao": "DSV" },
    { "country": "Romania", "name": "Medallion Air", "icao": "MDP" },
    { "country": "Australia", "name": "Orchid Airlines", "icao": "ORC" },
    { "country": "Kazakhstan", "name": "Asia Wings", "icao": "AWA" },
    { "country": "Georgia", "name": "Georgian International Airlines", "icao": "GNN" },
    { "country": "Georgia", "name": "Air Batumi", "icao": "BTM" },
    { "country": "Australia", "name": "Skywest Australia", "icao": "\\N" },
    { "country": "Egypt", "name": "Nile Air", "icao": "NIA" },
    { "country": "Sudan", "name": "Feeder Airlines", "icao": "FDD" },
    { "country": "Senegal", "name": "Senegal Airlines", "icao": "SGG" },
    { "country": "Ghana", "name": "Starbow Airlines", "icao": "\\N" },
    { "country": "Denmark", "name": "Copenhagen Express", "icao": "CX0" },
    { "country": "Thailand", "name": "BusinessAir", "icao": "BCC" },
    { "country": "United States", "name": "SENIC AIRLINES", "icao": "\\N" },
    { "country": "United States", "name": "XOJET", "icao": "XOJ" },
    { "country": "South Korea", "name": "Sky Wing Pacific", "icao": "CR7" },
    { "country": "South Africa", "name": "Bateleur Air", "icao": "BEU" },
    { "country": "Pakistan", "name": "Air Indus", "icao": "AI0" },
    { "country": "United States", "name": "Orbit International Airlines", "icao": "OAI" },
    { "country": "United States", "name": "Orbit Regional Airlines", "icao": "OAR" },
    { "country": "United States", "name": "Orbit Atlantic Airways", "icao": "OAN" },
    { "country": "Spain", "name": "Volotea", "icao": "VOO" },
    { "country": "Japan", "name": "Peach Aviation", "icao": "\\N" },
    { "country": "Spain", "name": "Helitt Líneas Aéreas", "icao": "HTH" },
    { "country": "Russia", "name": "Russia State Transport", "icao": "RSD" },
    { "country": "Malaysia", "name": "Malaysia Wings", "icao": "MWI" },
    { "country": "Russia", "name": "Aviabus", "icao": "ABI" },
    { "country": "Puerto Rico", "name": "Michael Airlines", "icao": "MJG" },
    { "country": "Congo (Kinshasa)", "name": "Korongo Airlines", "icao": "KGO" },
    { "country": "Indonesia", "name": "Indonesia Sky", "icao": "IDS" },
    { "country": "United States", "name": "Aws express", "icao": "666" },
    { "country": "United States", "name": "Southjet", "icao": "SJS" },
    { "country": "United States", "name": "Southjet connect", "icao": "ZCS" },
    { "country": "United States", "name": "Southjet cargo", "icao": "XAN" },
    { "country": "Spain", "name": "Iberia Express", "icao": "IBS" },
    { "country": "Mexico", "name": "Interjet (ABC Aerolineas)", "icao": "\\N" },
    { "country": "Ukraine", "name": "AirOnix", "icao": "\\N" },
    { "country": "Finland", "name": "Nordic Global Airlines", "icao": "NGB" },
    { "country": "Singapore", "name": "Scoot", "icao": "SCO" },
    { "country": "Portugal", "name": "Hi Fly (5K)", "icao": "\\N" },
    { "country": "China", "name": "China Northwest Airlines (WH)", "icao": "\\N" },
    { "country": "Thailand", "name": "Zenith International Airline", "icao": "ZNA" },
    { "country": "Azerbaijan", "name": "Orbit Airlines Azerbaijan", "icao": "OAB" },
    { "country": "Austria", "name": "Air Alps Aviation (A6)", "icao": "\\N" },
    { "country": "Australia", "name": "Flying kangaroo Airline", "icao": "FKA" },
    { "country": "Russia", "name": "RusJet", "icao": "RSJ" },
    { "country": "Vietnam", "name": "VietJet Air", "icao": "VJC" },
    { "country": "United States", "name": "Patriot Airways", "icao": "\\N" },
    { "country": "United States", "name": "Vision Airlines (V2)", "icao": "RBY" },
    { "country": "Uruguay", "name": "BQB Lineas Aereas", "icao": "\\N" },
    { "country": "Japan", "name": "AirAsia Japan", "icao": "WAJ" },
    { "country": "United States", "name": "Yellowtail", "icao": "YEL" },
    { "country": "United States", "name": "Royal Airways", "icao": "RAW" },
    { "country": "Ireland", "name": "FlyHigh Airlines Ireland (FH)", "icao": "FHI" },
    { "country": "United States", "name": "Executive AirShare", "icao": "XSR" },
    { "country": "China", "name": "Hebei Airlines", "icao": "HBH" },
    { "country": "Burma", "name": "Air KBZ", "icao": "KBZ" },
    { "country": "Portugal", "name": "Aero VIP (2D)", "icao": "\\N" },
    { "country": "Burma", "name": "Yangon Airways Ltd.", "icao": "\\N" },
    { "country": "United States", "name": "T.J. Air", "icao": "TJA" },
    { "country": "Switzerland", "name": "SkyWork Airlines ", "icao": "\\N" },
    { "country": "Netherlands", "name": "Maastricht Airlines", "icao": "\\N" },
    { "country": "Germany", "name": "Euro Jet", "icao": "\\N" },
    { "country": "Ukraine", "name": "Ukraine Atlantic", "icao": "UAT" },
    { "country": "Egypt", "name": "Nesma Airlines", "icao": "NMA" },
    { "country": "Afghanistan", "name": "East Horizon", "icao": "EHN" },
    { "country": "Peru", "name": "Air Majoro", "icao": "MJP" },
    { "country": "United Arab Emirates", "name": "Rotana Jet", "icao": "RJD" },
    { "country": "Russia", "name": "SOCHI AIR CHATER", "icao": "QER" },
    { "country": "Norway", "name": "Denim Air ", "icao": "\\N" },
    { "country": "Malaysia", "name": "Malindo Air", "icao": "MXD" },
    { "country": "Greece", "name": "Hermes Airlines", "icao": "HRM" },
    { "country": "Tanzania", "name": "Flightlink Tanzania", "icao": "\\N" },
    { "country": "Russia", "name": "IzAvia", "icao": "\\N" },
    { "country": "Russia", "name": "Катэкавиа", "icao": "КТК" },
    { "country": "Russia", "name": "Псковавиа", "icao": "PKV" },
    { "country": "United States", "name": "Maryland Air", "icao": "M1F" },
    { "country": "Netherlands Antilles", "name": "Insel Air (7I/INC) (Priv)", "icao": "\\N" },
    { "country": "Colombia", "name": "VivaColombia", "icao": "VVC" },
    { "country": "Finland", "name": "Flybe Finland Oy", "icao": "FCM" },
    { "country": "Poland", "name": "Bingo Airways", "icao": "BGY" },
    { "country": "Greece", "name": "Bluebird Airways (BZ)", "icao": "BBG" },
    { "country": "United States", "name": "Apache Air", "icao": "IWA" },
    { "country": "Germany", "name": "MHS Aviation GmbH", "icao": "\\N" },
    { "country": "Hong Kong", "name": "Jettor Airlines", "icao": "JTO" },
    { "country": "Maldives", "name": "Flyme (VP)", "icao": "VQI" },
    { "country": "Thailand", "name": "Thai Lion Air", "icao": "TLM" },
    { "country": "Burma", "name": "Golden Myanmar Airlines", "icao": "GMR" },
    { "country": "Spain", "name": "Canaryfly", "icao": "CNF" },
    { "country": "Haiti", "name": "Sunrise Airways", "icao": "KSZ" },
    { "country": "United States", "name": "National Air Cargo", "icao": "NCR" },
    { "country": "United States", "name": "Eastern Atlantic Virtual Airlines", "icao": "EAV" },
    { "country": "Indonesia", "name": "Citilink Indonesia", "icao": "\\N" },
    { "country": "Canada", "name": "Transair", "icao": "TTZ" },
    { "country": "United States", "name": "Comfort Express Virtual Charters Albany", "icao": "EVC" },
    { "country": "United States", "name": "Comfort Express Virtual Charters", "icao": "CEO" },
    { "country": "Poland", "name": "FLYJET", "icao": "FYJ" },
    { "country": "Finland", "name": "Snowbird Airlines", "icao": "SBD" },
    { "country": "Russia", "name": "Russkie Krylya", "icao": "KRY" },
    { "country": "Ukraine", "name": "Kharkiv Airlines", "icao": "KHK" },
    { "country": "United States", "name": "XAIR USA", "icao": "XAU" },
    { "country": "India", "name": "Air Costa", "icao": "\\N" },
    { "country": "Nepal", "name": "Simrik Airlines", "icao": "RMK" },
    { "country": "Portugal", "name": "XPTO", "icao": "XPT" },
    { "country": "Russia", "name": "Royal Flight", "icao": "DME" },
    { "country": "United Kingdom", "name": "BBN-Airways", "icao": "EGH" },
    { "country": "Russia", "name": "Tomsk-Avia", "icao": "TKS" },
    { "country": "Malawi", "name": "Malawian Airlines", "icao": "\\N" },
    { "country": "Nepal", "name": "Yeti Airlines ", "icao": "NYT" },
    { "country": "Switzerland", "name": "Avilu", "icao": "..." },
    { "country": "Turkey", "name": "Skyline Ulasim Ticaret A.S.", "icao": "KCU" },
    { "country": "United States", "name": "Envoy Air", "icao": "ENY" },
    { "country": "Barbados", "name": "CARICOM AIRWAYS (BARBADOS) INC.", "icao": "CCB" },
    { "country": "United States", "name": "Rainbow Air (RAI)", "icao": "RAB" },
    { "country": "Canada", "name": "Rainbow Air Canada", "icao": "RAY" },
    { "country": "United States", "name": "Rainbow Air Polynesia", "icao": "RPO" },
    { "country": "United Kingdom", "name": "Rainbow Air Euro", "icao": "RUE" },
    { "country": "United States", "name": "Rainbow Air US", "icao": "RNY" },
    { "country": "Romania", "name": "Transilvania", "icao": "TNS" },
    { "country": "Russia", "name": "Dobrolet", "icao": "DOB" },
    { "country": "United States", "name": "Spike Airlines", "icao": "SAL" },
    { "country": "Lithuania", "name": "Grand Cru Airlines", "icao": "GCA" },
    { "country": "Slovakia", "name": "Go2Sky", "icao": "RLX" },
    { "country": "Argentina", "name": "All Argentina", "icao": "AL1" },
    { "country": "United States", "name": "All America", "icao": "AL2" },
    { "country": "China", "name": "All Asia", "icao": "AL3" },
    { "country": "South Africa", "name": "All Africa", "icao": "99F" },
    { "country": "Mexico", "name": "Regionalia México", "icao": "J88" },
    { "country": "United Kingdom", "name": "All Europe", "icao": "N99" },
    { "country": "Spain", "name": "All Spain", "icao": "N77" },
    { "country": "Iceland", "name": "Regional Air Iceland", "icao": "N78" },
    { "country": "Brazil", "name": "Voestar", "icao": "K88" },
    { "country": "Colombia", "name": "All Colombia", "icao": "7KK" },
    { "country": "Uruguay", "name": "Regionalia Uruguay", "icao": "2K2" },
    { "country": "Venezuela", "name": "Regionalia Venezuela", "icao": "9XX" },
    { "country": "Chile", "name": "Regionalia Chile", "icao": "CR1" },
    { "country": "Cuba", "name": "Vuela Cuba", "icao": "6CC" },
    { "country": "Australia", "name": "All Australia", "icao": "8K8" },
    { "country": "Spain", "name": "Fly Europa", "icao": "RWW" },
    { "country": "Portugal", "name": "FlyPortugal", "icao": "FPT" },
    { "country": "Myanmar", "name": "Myanmar Airways International", "icao": "MMA" },
    { "country": "India", "name": "Vistera", "icao": "VTI" },
    { "country": "China", "name": "Urumqi Air", "icao": "CUH" },
    { "country": "China", "name": "Guangxi Beibu Gulf Airlines", "icao": "CBG" },
    { "country": "Indonesia", "name": "My Indo Airlines", "icao": "MYU" },
    { "country": "Morocco", "name": "Government of Morocco", "icao": "FRV" },
    { "country": "Hong Kong", "name": "Hong Kong Air Cargo", "icao": "HKC" },
    { "country": "Bangladesh", "name": "US-Bangla Airlines", "icao": "UBG" },
    { "country": "Portugal", "name": "NetJets Europe", "icao": "NJE" },
    { "country": "Bhutan", "name": "Bhutan Airlines", "icao": "BTN" },
    { "country": "Bhutan", "name": "Iran Airtour", "icao": "IRB" },
    { "country": "Austria", "name": "Avcon Jet", "icao": "AOJ" },
    { "country": "Indonesia", "name": "Indonesia AirAsia X", "icao": "IDX" },
    { "country": "Qatar", "name": "Qatar Executive", "icao": "QQE" },
    { "country": "China", "name": "SF Airlines", "icao": "CSS" },
    { "country": "Bangladesh", "name": "Regent Airways", "icao": "RGE" },
    { "country": "Malaysia", "name": "AsiaCargo Express", "icao": "CXM" }

  ]



